/**
 * the fixture-provenance surface fixture provenance registry — the shared record contract.
 *
 * One `FixtureProvenanceRecord` per frozen byte fixture the package ships, indexed by an
 * immutable `fixtureId`. The registry is metadata ABOUT frozen fixtures: it records provenance
 * and pins digests, and it never stores fixture bytes themselves, so it can never become an
 * alternate byte source that silently diverges from the file it describes ("Expected
 * bytes are stored as bytes or an unambiguous byte encoding, never regenerated by the
 * implementation under test").
 *
 * Digest rule (byte-exact-signing adjacency): every `sha256` in a record is computed from the
 * actual frozen file, never hand-typed, and `verify.ts` recomputes it against the committed
 * bytes at test time, so a stale or fabricated digest fails the suite instead of drifting.
 */

/**
 * The three protocol byte classes of the protocol foundation — "conflating these
 * classes is a release-blocking defect":
 * - `signed-preimage`  — SplitChain signed preimages (JSON.stringify exact bytes that
 *   are, or embed, the signed surface; transfer codes and receive goldens live here).
 * - `suite-tuple`      — V2 suite canonical tuples (domain-separated `zp-*-v1` purposes:
 *   approvals and expected artifacts).
 * - `unsigned-evidence` — the unsigned raw-bytes-plus-digest class. Gateway response
 *   evidence is the protocol's instance; unsigned frozen vector/golden JSON (amount and
 *   event-commit vectors, pinned public keys) shares the same class property: retained raw
 *   bytes authenticated by digest, never by a signature.
 */
export const FIXTURE_BYTE_CLASSES = ["signed-preimage", "suite-tuple", "unsigned-evidence"] as const;

export type FixtureByteClass = (typeof FIXTURE_BYTE_CLASSES)[number];

/**
 * How the frozen bytes came to exist ("Golden bytes come from verified wallet/gateway
 * captures or a canonical constructor, with provenance recorded").
 */
export const FIXTURE_ORIGIN_KINDS = [
  "wallet-capture",
  "gateway-capture",
  "canonical-constructor",
] as const;

export type FixtureOriginKind = (typeof FIXTURE_ORIGIN_KINDS)[number];

/** One digested file of a fixture family. `path` is package-relative POSIX. */
export interface FixtureFileDigest {
  readonly path: string;
  /** Lowercase hex SHA-256 of the exact committed file bytes — computed, never hand-typed. */
  readonly sha256: string;
}

/**
 * Provenance block — the unified superset of the three pre-existing scattered shapes
 * (`goldens/transfer-code/*.meta.json` sidecars, `src/receive-golden/*\/manifest.json`
 * provenance blocks, and the `packages/splitchain` backup `*.provenance.json` field list).
 * Every required field is a non-empty string; where a field is not applicable to the origin
 * kind (e.g. `walletVersion` for a canonical constructor) the record carries an explicit
 * sentinel explaining why, never a silently-blank value.
 */
export interface FixtureProvenance {
  readonly originKind: FixtureOriginKind;
  /** How the bytes were captured or constructed, including the tool and verification steps. */
  readonly captureMethod: string;
  /**
   * ISO `YYYY-MM-DD` date the covered bytes entered their current frozen form (the freeze
   * commit's date). A fixture refresh is a contract change and must update this date.
   */
  readonly captureDate: string;
  /** Live-wallet version for wallet captures; an explicit `n/a — <reason>` sentinel otherwise. */
  readonly walletVersion: string;
  /** The canonical source of the bytes: mirror file/lines, generator script, or spec anchor. */
  readonly source: string;
  /** Key material behind the fixture — always a deterministic test-only seed, or `none`. */
  readonly keyMaterial: string;
  readonly specCitations: readonly string[];
  readonly decisionRefs: readonly string[];
  /** Family-specific extras (wallet line ranges, generator, constructor references, roles). */
  readonly details?: Readonly<Record<string, string>>;
}

/**
 * One immutable fixture id and everything the drift gate (the fixture-provenance drift gate) needs to police it.
 * `indexPath` is the file a reviewer finds with
 * `find packages/generic-node-contracts -iname '*.meta.json' -o -iname 'manifest.json' -o -iname '*.vectors.json'`;
 * `files` digests the index file plus every frozen sibling byte file of the family, so a
 * mutation anywhere in the family reddens the integrity check.
 */
export interface FixtureProvenanceRecord {
  readonly fixtureId: string;
  readonly byteClass: FixtureByteClass;
  readonly indexPath: string;
  readonly files: readonly FixtureFileDigest[];
  readonly provenance: FixtureProvenance;
}
