import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  encodeTransferCode,
  decodeTransferCode,
  transferCodeSha256,
  sha256Utf8,
} from "./transfer-code-codec.ts";
import { buildGatewayRequestBody } from "./gateway-transport-codec.ts";

/**
 * the receive-golden transfer-code concern.3 wallet-parity and mutation vectors. Reads the raw digest-pinned goldens in
 * goldens/transfer-code/ (never regenerated by this test — A8: no committed test writes a golden),
 * proves encode/decode parity and inner retention against A.8, and asserts that every
 * byte mutation (resequence, whitespace, ms-vs-seconds, wrong version, truncation, signature, and
 * partial/full boundary) fails the frozen byte contract.
 */
const goldenDir = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "goldens",
  "transfer-code",
);
const readGolden = (name: string): string => readFileSync(join(goldenDir, name), "utf8");

// Frozen digests (SHA-256 of the exact golden bytes). A change to any golden must be a reviewed,
// deliberate byte-contract change that updates these constants.
const RECEIVE_B64URL_SHA256 = "104eb00c3bda958b82b7ce5a24e582dd9efa3e63d2192838fe26b5b23dcb2bab";
const RECEIVE_JSON_SHA256 = "6884acef681a435f7ef04b82c0d6d5df28c8f12275c2c69063d721ae6dcd0869";
const SEND_B64URL_SHA256 = "d454846fddc861c059476553ec4fe03fdbf3cb494a0b5be6357ceb8049d6d0e4";
const SEND_JSON_SHA256 = "fc0af28b7232f2b83df93a39dac0bd1ddedcd477e658af23b49de49e3ed09640";

// Exact A.8 SplitChain step-1 preimage and signature (the SEND code keeps these bytes verbatim).
const A8_STEP1_PREIMAGE =
  '{"type":"unique_combinable","version":"2","unix_time_secs":"1784332800.125","signer_steps":2,"step_1_signer":"sender","step_2_signer":"receiver","step_1_key_public__base64urlsafe":"gTl3Dqh9F19Wo1Rmw0x-zMuNipG07jeiXfYPW4_Js5Q=","step_2_key_public__base64urlsafe":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","step_1_state":{"amount":"7.75"},"step_2_state":{"amount":"2.25"},"previous_step_1_state_signature":"","previous_step_2_state_signature":"","expiry__unix_time_secs":"1784336400","message":"zp1:33333333-3333-4333-8333-333333333333:ord_7YQ3"}';
const A8_STEP1_SIGNATURE =
  "Rq6Oyn7HEISIb1t3dRuSv-czb33rsWAUmiZe2YmBTK813iHOfNXGF8fIzenv_UENGqUzKJl6f1iTpeAMfnHeAA==";

const receiveB64 = readGolden("receive-code.v1.b64url.txt");
const receiveJson = readGolden("receive-code.v1.json.txt");
const sendB64 = readGolden("send-code.v1.b64url.txt");
const sendJson = readGolden("send-code.v1.json.txt");

// Raw-JSON encoder for byte mutations that operate on the JSON preimage text directly.
const encodeRawJson = (json: string): string =>
  Buffer.from(encodeURIComponent(json), "utf8").toString("base64url").replace(/=/g, "");

interface ReceiveEnvelope {
  version: string;
  type: string;
  incoming_data: {
    receiver_key_public__base64urlsafe: string;
    inner_state_amount: string;
    expiry__unix_time_secs: string;
    message: string;
  };
}

interface SendEnvelope {
  version: string;
  type: string;
  incoming_data: {
    partial_transaction: { inner: Record<string, unknown>; step_1_signature: string };
  };
}

describe("transfer-code goldens: digest pins and parity (the receive-golden transfer-code concern.3)", () => {
  it("has no trailing newline in the raw byte goldens", () => {
    for (const raw of [receiveB64, receiveJson, sendB64, sendJson]) {
      expect(raw.endsWith("\n")).toBe(false);
    }
  });

  it("digest-pins the RECEIVE goldens (sender_create_transaction v1)", () => {
    expect(transferCodeSha256(receiveB64)).toBe(RECEIVE_B64URL_SHA256);
    expect(sha256Utf8(receiveJson)).toBe(RECEIVE_JSON_SHA256);
  });

  it("digest-pins the SEND goldens (receiver_confirm_partial_transaction v1)", () => {
    expect(transferCodeSha256(sendB64)).toBe(SEND_B64URL_SHA256);
    expect(sha256Utf8(sendJson)).toBe(SEND_JSON_SHA256);
  });

  it("decode(encoded) equals the JSON preimage golden byte-for-byte", () => {
    expect(JSON.stringify(decodeTransferCode(receiveB64))).toBe(receiveJson);
    expect(JSON.stringify(decodeTransferCode(sendB64))).toBe(sendJson);
  });

  it("encode(JSON preimage) round-trips to the exact encoded golden", () => {
    expect(encodeTransferCode(JSON.parse(receiveJson))).toBe(receiveB64);
    expect(encodeTransferCode(JSON.parse(sendJson))).toBe(sendB64);
  });

  it("keeps the exact A.8 signed inner and step-1 signature verbatim in the SEND code", () => {
    const send = decodeTransferCode(sendB64) as SendEnvelope;
    const partial = send.incoming_data.partial_transaction;
    expect(JSON.stringify(partial.inner)).toBe(A8_STEP1_PREIMAGE);
    expect(partial.step_1_signature).toBe(A8_STEP1_SIGNATURE);
    // A partial carries no step_2_signature key.
    expect(Object.keys(partial)).toEqual(["inner", "step_1_signature"]);
  });
});

describe("transfer-code mutation vectors — each MUST fail (the receive-golden transfer-code concern.3)", () => {
  it("resequenced top-level keys change the bytes", () => {
    const recv = decodeTransferCode(receiveB64) as ReceiveEnvelope;
    const resequenced = { type: recv.type, version: recv.version, incoming_data: recv.incoming_data };
    expect(transferCodeSha256(encodeTransferCode(resequenced))).not.toBe(RECEIVE_B64URL_SHA256);
  });

  it("whitespace injection into the JSON preimage changes the bytes", () => {
    const spaced = receiveJson.replace('"version":"1"', '"version": "1"');
    expect(spaced).not.toBe(receiveJson);
    expect(transferCodeSha256(encodeRawJson(spaced))).not.toBe(RECEIVE_B64URL_SHA256);
  });

  it("a milliseconds expiry is a different byte string than the seconds golden", () => {
    const recv = decodeTransferCode(receiveB64) as ReceiveEnvelope;
    expect(recv.incoming_data.expiry__unix_time_secs).toBe("1784336400"); // seconds
    const ms: ReceiveEnvelope = {
      ...recv,
      incoming_data: { ...recv.incoming_data, expiry__unix_time_secs: "1784336400000" },
    };
    expect(transferCodeSha256(encodeTransferCode(ms))).not.toBe(RECEIVE_B64URL_SHA256);
  });

  it("a wrong version literal changes the bytes", () => {
    const recv = decodeTransferCode(receiveB64) as ReceiveEnvelope;
    for (const wrong of ["2", "3"]) {
      const mutated: ReceiveEnvelope = { ...recv, version: wrong };
      expect(transferCodeSha256(encodeTransferCode(mutated))).not.toBe(RECEIVE_B64URL_SHA256);
    }
  });

  it("a truncated code does not decode to the golden", () => {
    const truncated = receiveB64.slice(0, receiveB64.length - 8);
    expect(() => decodeTransferCode(truncated)).toThrow();
  });

  it("mutating the step-1 signature changes the SEND bytes", () => {
    const send = decodeTransferCode(sendB64) as SendEnvelope;
    const mutated: SendEnvelope = {
      ...send,
      incoming_data: {
        partial_transaction: {
          inner: send.incoming_data.partial_transaction.inner,
          step_1_signature: `A${A8_STEP1_SIGNATURE.slice(1)}`,
        },
      },
    };
    expect(transferCodeSha256(encodeTransferCode(mutated))).not.toBe(SEND_B64URL_SHA256);
  });

  it("adding step_2_signature (partial -> full) changes the SEND bytes", () => {
    const send = decodeTransferCode(sendB64) as SendEnvelope;
    const asFull = {
      version: send.version,
      type: send.type,
      incoming_data: {
        partial_transaction: {
          inner: send.incoming_data.partial_transaction.inner,
          step_1_signature: send.incoming_data.partial_transaction.step_1_signature,
          step_2_signature: A8_STEP1_SIGNATURE,
        },
      },
    };
    expect(transferCodeSha256(encodeTransferCode(asFull))).not.toBe(SEND_B64URL_SHA256);
  });

  it("a non-encoded gateway form body differs from the frozen-built body", () => {
    const built = buildGatewayRequestBody("submit_transaction__v1", { a: "1" });
    const naive = 'v={"action_name":"submit_transaction__v1","action_data":{"a":"1"}}';
    expect(built).not.toBe(naive);
  });
});

describe("the retained partial inner tracks the published golden inner", () => {
  // The freeze publishes the step-1 preimage's digest alongside the preimage itself.
  // Pinning the published digest as an independent constant keeps the cross-check honest: the
  // retained `A8_STEP1_PREIMAGE` constant above and this digest were transcribed separately, so
  // a byte edit to either one fails here instead of drifting both in lockstep.
  //
  // Provenance note ("Two roles, one object (byte-identical)"): this empty-
  // previous_step_1_state_signature inner is retained here as the valid SEND partial
  // (receiver_confirm_partial_transaction v1) but is byte-for-byte the SAME object as the
  // funded-sender-genesis-predecessor negative RECEIVE vector (vector 17, rejected) — one
  // object, two roles. It is a distinct object from the positive RECEIVE golden (digest
  // ce0741df...) and unrelated to the SEND_EXTERNAL redemption inner (a separate operation
  // kind governed by SEND_REDEMPTION_WINDOW_SECS). Do not label this fixture plain "SEND" —
  // it is a dual-role object.
  const A80_PUBLISHED_STEP1_SHA256 =
    "f0e12e993cc4d6b452162cd49b2699b9f912d7a2bf3d8ddd418e3a29c6bbf0b7";

  it("the published step_1_sha256 equals the retained partial inner's digest", () => {
    expect(sha256Utf8(A8_STEP1_PREIMAGE)).toBe(A80_PUBLISHED_STEP1_SHA256);
  });
});
