import { beforeAll, describe, expect, it } from "vitest";

import {
  ready,
  keypairFromSeedByte,
  encodeBase64Url,
  digestPreimage,
  signPreimage,
  verifyPreimageSignature,
  utf8Bytes,
  decodeBase64Url,
  verifyDetached,
  type RawKeypair,
} from "../testkit/independentCrypto.ts";
import { readGoldenText, sha256OfGolden } from "../testkit/byteGolden.ts";
import { hasSuiteDomainPrefix } from "./verify.ts";

/**
 * The wallet-faithfulness proof for the approval golden (the approval-tuple schema). An INDEPENDENT implementation
 * (`src/testkit/independentCrypto.ts`, pinned to the wallet's libsodium family) re-derives the
 * device approval key from the published deterministic seed byte 0x01 and reproduces the pinned
 * SHA-256 and the OPTIONAL additive Ed25519 device signature in appendix A.8 from the raw
 * preimage golden on disk. The golden is never regenerated by this code — it is read and asserted
 * against. The device seed-byte key is test-only and MUST never sign live ZKZ (A.8; A.9 vector 16).
 */
const DEVICE_SEED_BYTE = 0x01;
const PURPOSE = "zp-send-external-approval-v1";

let deviceKeypair: RawKeypair;

beforeAll(async () => {
  await ready();
  deviceKeypair = keypairFromSeedByte(DEVICE_SEED_BYTE);
});

const preimage = (): string => readGoldenText(`approval/${PURPOSE}.preimage.txt`);
const pinnedDigest = (): string => readGoldenText(`approval/${PURPOSE}.digest.hex`);
const pinnedSig = (): string => readGoldenText(`approval/${PURPOSE}.sig.b64`);

describe("appendix A.8 approval deterministic reproduction proof (the approval-tuple schema)", () => {
  it("reproduces the pinned device public key from seed byte 0x01", () => {
    expect(encodeBase64Url(deviceKeypair.publicKey)).toBe("iojj3XQJ8ZX9UtstPLpdcspnCb8dlBIb83SIAbQPb1w=");
  });

  it("the preimage's domain-separation prefix is the approval purpose", () => {
    expect(preimage().slice(0, preimage().indexOf("\n"))).toBe(PURPOSE);
    expect(hasSuiteDomainPrefix(preimage())).toBe(true);
  });

  it("reproduces the pinned SHA-256 digest from the exact preimage bytes", () => {
    expect(digestPreimage(preimage())).toBe(pinnedDigest());
    expect(pinnedDigest()).toBe("d7c03561bd9bc87e302c533f03741c34d44058fc0aaf1b59b17a4f28f8022146");
  });

  it("the preimage file's own SHA-256 equals the pinned artifact digest (A.8 invariant)", () => {
    expect(sha256OfGolden(`approval/${PURPOSE}.preimage.txt`)).toBe(pinnedDigest());
  });

  it("reproduces the pinned additive device Ed25519 signature (wallet-faithfulness)", () => {
    expect(signPreimage(preimage(), deviceKeypair.privateKey)).toBe(pinnedSig());
    expect(pinnedSig()).toBe(
      "HLd6EN7uw2KHCgRAryuyEh6ljmHsjgvCJ6Ke1Gq3fb0PDV1Vsn3QCzuo51o0VnH9LCbDI3c_s6AFK3NO013ZCA==",
    );
  });

  it("the pinned device signature verifies against the reproduced device public key", () => {
    expect(verifyPreimageSignature(preimage(), pinnedSig(), deviceKeypair.publicKey)).toBe(true);
  });

  it("approval-preimage isolation: the device signature does NOT verify over prefix-less SplitChain-style bytes (A.9 vector 15)", () => {
    // The SplitChain native serializer (A.1.2) has NO purpose prefix. Stripping the prefix yields
    // the byte form a SplitChain preimage would take; the approval signature must not verify over
    // it, proving the two schemes never share signable bytes.
    const suite = preimage();
    const splitchainStyle = suite.slice(suite.indexOf("\n") + 1);
    expect(hasSuiteDomainPrefix(splitchainStyle)).toBe(false);
    expect(
      verifyDetached(decodeBase64Url(pinnedSig()), utf8Bytes(splitchainStyle), deviceKeypair.publicKey),
    ).toBe(false);
  });
});
