#!/usr/bin/env node
// Local/compose secret generator for generic-node deploy.
// Primary path for docker compose; Railway uses ${{secret(...)}} generators (catalog).
// Never commits secrets. vault KEK ≠ backup KEK enforced.

import { randomBytes, randomUUID } from "node:crypto";
import { writeFileSync, chmodSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const usage = `Usage: node apps/generic-node/scripts/generate-secrets.mjs [options]

Generate distinct deploy secrets for generic-node (zunode) and print the setup wizard URL.

Options:
  --out <path>       Write KEY=value env file (mode 0600). Default: stdout only.
  --public-base-url  PUBLIC_BASE_URL for setup link (default: http://127.0.0.1:8787)
  --force            Overwrite --out if it exists
  --dry-run          Generate and validate only; never write (implies no --out write)
  --json             Machine-readable summary (no secret values in JSON)
  --help             Show this help

Generated (never logged in full except via --out / stdout env block):
  NODE_ID                 lowercase UUID
  VAULT_MASTER_KEY        64 hex chars (≥32 entropy)
  BACKUP_MASTER_KEY       64 hex chars, MUST ≠ VAULT_MASTER_KEY
  INITIAL_ADMIN_PASSWORD  32 hex chars

After the process is ready, open:
  \${PUBLIC_BASE_URL}/setup
`;

function parseArgs(argv) {
  const out = {
    outPath: null,
    publicBaseUrl: "http://127.0.0.1:8787",
    force: false,
    dryRun: false,
    json: false,
    help: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--help" || a === "-h") out.help = true;
    else if (a === "--force") out.force = true;
    else if (a === "--dry-run") out.dryRun = true;
    else if (a === "--json") out.json = true;
    else if (a === "--out") {
      out.outPath = argv[++i];
      if (!out.outPath) throw new Error("--out requires a path");
    } else if (a === "--public-base-url") {
      out.publicBaseUrl = argv[++i];
      if (!out.publicBaseUrl) throw new Error("--public-base-url requires a value");
    } else {
      throw new Error(`unknown argument: ${a}`);
    }
  }
  return out;
}

/** Cryptographically strong hex string of `bytes` random bytes. */
export function randomHex(bytes) {
  return randomBytes(bytes).toString("hex");
}

/**
 * Produce a secret set with vault ≠ backup KEK (retry if collision — astronomically rare).
 */
export function generateSecretSet() {
  const nodeId = randomUUID().toLowerCase();
  let vault = randomHex(32);
  let backup = randomHex(32);
  let guard = 0;
  while (backup === vault) {
    backup = randomHex(32);
    if (++guard > 5) throw new Error("failed to produce distinct BACKUP_MASTER_KEY");
  }
  const initialAdminPassword = randomHex(16);
  return {
    NODE_ID: nodeId,
    VAULT_MASTER_KEY: vault,
    BACKUP_MASTER_KEY: backup,
    INITIAL_ADMIN_PASSWORD: initialAdminPassword,
  };
}

export function assertVaultNeBackup(secrets) {
  if (secrets.VAULT_MASTER_KEY === secrets.BACKUP_MASTER_KEY) {
    throw new Error("VAULT_MASTER_KEY must not equal BACKUP_MASTER_KEY");
  }
  if (secrets.VAULT_MASTER_KEY.length < 32 || secrets.BACKUP_MASTER_KEY.length < 32) {
    throw new Error("master keys must be ≥32 characters");
  }
}

export function setupWizardUrl(publicBaseUrl) {
  const base = publicBaseUrl.replace(/\/+$/, "");
  return `${base}/setup`;
}

export function formatEnvFile(secrets, extras = {}) {
  const lines = [
    "# Generated by apps/generic-node/scripts/generate-secrets.mjs — DO NOT COMMIT",
    "# vault KEK ≠ backup KEK (separate custody domains). After boot open SETUP_URL.",
    `NODE_ID=${secrets.NODE_ID}`,
    `VAULT_MASTER_KEY=${secrets.VAULT_MASTER_KEY}`,
    `BACKUP_MASTER_KEY=${secrets.BACKUP_MASTER_KEY}`,
    `INITIAL_ADMIN_PASSWORD=${secrets.INITIAL_ADMIN_PASSWORD}`,
  ];
  for (const [k, v] of Object.entries(extras)) {
    lines.push(`${k}=${v}`);
  }
  lines.push("");
  return lines.join("\n");
}

function main(argv = process.argv.slice(2)) {
  const args = parseArgs(argv);
  if (args.help) {
    process.stdout.write(usage);
    return 0;
  }

  const secrets = generateSecretSet();
  assertVaultNeBackup(secrets);
  const setupUrl = setupWizardUrl(args.publicBaseUrl);
  const extras = {
    PUBLIC_BASE_URL: args.publicBaseUrl.replace(/\/+$/, ""),
    SETUP_URL: setupUrl,
    // Non-secret defaults for local compose happy path
    BACKUP_SCHEDULE_ENABLED: "true",
    BACKUP_OUTPUT_DIR: "/var/lib/generic-node/backups",
    NODE_ENV: "development",
  };

  if (args.json) {
    process.stdout.write(
      JSON.stringify(
        {
          ok: true,
          vault_ne_backup: secrets.VAULT_MASTER_KEY !== secrets.BACKUP_MASTER_KEY,
          node_id_is_uuid: /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(
            secrets.NODE_ID,
          ),
          vault_key_len: secrets.VAULT_MASTER_KEY.length,
          backup_key_len: secrets.BACKUP_MASTER_KEY.length,
          setup_url: setupUrl,
          wrote: false,
        },
        null,
        2,
      ) + "\n",
    );
  }

  const envBody = formatEnvFile(secrets, extras);

  if (args.dryRun) {
    if (!args.json) {
      process.stderr.write(
        `[dry-run] vault≠backup=${secrets.VAULT_MASTER_KEY !== secrets.BACKUP_MASTER_KEY} setup=${setupUrl}\n`,
      );
    }
    return 0;
  }

  if (args.outPath) {
    const abs = resolve(args.outPath);
    if (existsSync(abs) && !args.force) {
      throw new Error(`refusing to overwrite ${abs} (pass --force)`);
    }
    writeFileSync(abs, envBody, { encoding: "utf8", mode: 0o600 });
    try {
      chmodSync(abs, 0o600);
    } catch {
      /* best effort on platforms without chmod */
    }
    process.stderr.write(`Wrote secrets to ${abs} (mode 0600)\n`);
    process.stderr.write(`Next: start the node, then open ${setupUrl}\n`);
    process.stderr.write(
      "Primary: generator pre-seals env (this script). Alt: Railway ${{secret()}} template generators — see test/railway-template-catalog.ts\n",
    );
  } else if (!args.json) {
    process.stdout.write(envBody);
    process.stderr.write(`\n# Open setup wizard after ready: ${setupUrl}\n`);
    process.stderr.write(
      "# Primary path: this generator. Alt: Railway one-click ${{secret()}} (railway-template-catalog).\n",
    );
  }

  return 0;
}

// Only auto-run when executed as a CLI entry (not when vitest imports the module).
import { pathToFileURL } from "node:url";
const entry = process.argv[1] !== undefined ? pathToFileURL(resolve(process.argv[1])).href : "";
const isMain = entry !== "" && import.meta.url === entry;

if (isMain) {
  try {
    process.exitCode = main();
  } catch (err) {
    process.stderr.write(`generate-secrets: ${err instanceof Error ? err.message : String(err)}\n`);
    process.exitCode = 1;
  }
}
