// concern-local public surface. Package-root assembly is owned separately.

export {
  type NonceClaim,
  type NonceClaimOutcome,
  type NonceClaimResult,
  type ReportingNoncePurpose,
  type RegistrationEvidenceMode,
  type ReportingRouteClass,
  type DownstreamResult,
  type BurnDecisionOutcome,
  type BurnDecision,
  type LifecycleCommitOutcome,
  type LifecycleCommitResult,
  type LifecycleHead,
  type LifecycleEvent,
  type LifecycleKeyTransition,
  type AuthoritativeKeyState,
  type ReportingKeyState,
  type ReportingLifecycleEventType,
  type ReportingKeyEligibilityState,
  type RegistrationEvidenceOutcome,
  type RegistrationCrossBinding,
  type RegistrationCrossBindingOutcome,
  type DurableRegistrationNonceEvidence,
  type DurableEnrolmentEvidence,
  type BootstrapEvidenceProjection,
  type RotationAuthorizerEvidence,
  type LogicalFingerprintInput,
  type PersistedExactResponse,
  type MutationBindingProjection,
  type MutationAtomicityOutcome,
  type RestoreMarkers,
  type ExternalRestoreAuthority,
  type RestoredReportingState,
  type GuardedFingerprintClaim,
  type CompletedIdempotencyResult,
  type PostBurnOutcome,
  type PostBurnDecision,
  NONCE_UNIQUENESS_FIELDS,
  NONCE_SCOPE_EXCLUDED_FIELDS,
  REPORTING_NONCE_PURPOSES,
  REPORTING_NONCE_FIELDS,
  REPORTING_KEY_ID_NULLABILITY,
  REPORTING_SIGNED_WINDOW_MS,
  PRE_BURN_CHECKS,
  BURN_TRANSACTION_STEPS,
  POST_BURN_STAGES,
  MUTATION_IDEMPOTENCY_UNIQUENESS_FIELDS,
  LOGICAL_FINGERPRINT_FIELDS,
  LOGICAL_FINGERPRINT_EXCLUDED_FIELDS,
  FINGERPRINT_GUARDED_ROUTE_IDS,
  GUARDED_FINGERPRINT_UNIQUENESS_FIELDS,
  GUARDED_FINGERPRINT_PARTIAL_UNIQUENESS,
  MUTATION_IDEMPOTENCY_FIELDS,
  MUTATION_IDEMPOTENCY_PERSISTENCE,
  MUTATION_EVIDENCE_BINDING_FIELDS,
  MUTATION_EVIDENCE_IMMUTABILITY,
  MUTATION_ROUTE_RETENTION,
  REPORTING_LIFECYCLE_HEAD_FIELDS,
  REPORTING_LIFECYCLE_EVENT_UNIQUENESS_FIELDS,
  REPORTING_LIFECYCLE_EVENT_FIELDS,
  REPORTING_KEY_STATES,
  REPORTING_LIFECYCLE_EVENT_TYPES,
  LEGAL_LIFECYCLE_KEY_TRANSITIONS,
  LIFECYCLE_EVENT_HASH_CHAIN,
  REPORTING_KEY_IDENTITY_ALLOWED_FIELDS,
  REPORTING_KEY_IDENTITY_FORBIDDEN_FIELDS,
  REPORTING_KEY_OVERLAP_MS,
  REGISTRATION_EVIDENCE_MODES,
  REGISTRATION_EVIDENCE_FIELDS,
  IDEMPOTENCY_KEY_CONTRACT,
  REPORTING_RETENTION,
  RESTORE_POLICY,
  nonceClaimHasValidKeySemantics,
  reportingSignedWindowIsValid,
  nonceRetentionForRoute,
  claimSharedNonce,
  decideReportingBurn,
  commitLifecycleHead,
  priorKeyEligible,
  evaluateRegistrationEvidence,
  evaluateRegistrationCrossBinding,
  sameLogicalFingerprint,
  persistExactResponse,
  replayExactResponse,
  decideMutationAtomicity,
  mutationEvidenceBindingsMatch,
  restoreRequiresAuthHold,
  reportingAdmissionAllowed,
  reportingKeyIdentityIsPublicOnly,
  idempotencyKeyIsValid,
  guardedFingerprintAlreadyClaimed,
  decidePostBurn,
} from "./decisions.js";

export {
  type ReportingPersistenceManifest,
  reportingPersistenceConcernManifest,
  buildReportingPersistenceManifest,
} from "./manifest.js";
