// Concern manifest for durable reporting replay, lifecycle, and mutation evidence.

import {
  BURN_TRANSACTION_STEPS,
  FINGERPRINT_GUARDED_ROUTE_IDS,
  GUARDED_FINGERPRINT_PARTIAL_UNIQUENESS,
  IDEMPOTENCY_KEY_CONTRACT,
  LEGAL_LIFECYCLE_KEY_TRANSITIONS,
  LIFECYCLE_EVENT_HASH_CHAIN,
  LOGICAL_FINGERPRINT_EXCLUDED_FIELDS,
  LOGICAL_FINGERPRINT_FIELDS,
  MUTATION_EVIDENCE_BINDING_FIELDS,
  MUTATION_EVIDENCE_IMMUTABILITY,
  MUTATION_IDEMPOTENCY_FIELDS,
  MUTATION_IDEMPOTENCY_PERSISTENCE,
  MUTATION_IDEMPOTENCY_UNIQUENESS_FIELDS,
  MUTATION_ROUTE_RETENTION,
  NONCE_SCOPE_EXCLUDED_FIELDS,
  NONCE_UNIQUENESS_FIELDS,
  POST_BURN_STAGES,
  PRE_BURN_CHECKS,
  REGISTRATION_EVIDENCE_FIELDS,
  REGISTRATION_EVIDENCE_MODES,
  REPORTING_KEY_IDENTITY_ALLOWED_FIELDS,
  REPORTING_KEY_IDENTITY_FORBIDDEN_FIELDS,
  REPORTING_KEY_ID_NULLABILITY,
  REPORTING_KEY_OVERLAP_MS,
  REPORTING_KEY_STATES,
  REPORTING_LIFECYCLE_EVENT_TYPES,
  REPORTING_LIFECYCLE_EVENT_FIELDS,
  REPORTING_LIFECYCLE_EVENT_UNIQUENESS_FIELDS,
  REPORTING_LIFECYCLE_HEAD_FIELDS,
  REPORTING_NONCE_FIELDS,
  REPORTING_NONCE_PURPOSES,
  REPORTING_RETENTION,
  REPORTING_SIGNED_WINDOW_MS,
  RESTORE_POLICY,
} from "./decisions.js";

export const reportingPersistenceConcernManifest = {
  concern: "reporting-persistence",
  ticket: "reporting-persistence",
  frozen: [
    "SHARED_NONCE_LEDGER",
    "PRE_HANDLER_BURN_TRANSACTION",
    "REPORTING_LIFECYCLE_PERSISTENCE",
    "MUTATION_IDEMPOTENCY",
    "RESTORE_AND_RETENTION",
    "PUBLIC_KEY_ONLY_IDENTITY",
  ],
} as const;

export function buildReportingPersistenceManifest() {
  return {
    concern: reportingPersistenceConcernManifest.concern,
    ticket: reportingPersistenceConcernManifest.ticket,
    governing: {
      decisions: ["reporting-channel", "reporting-key-enrolment"],
      spec: [
        "reporting data model",
        "reporting API surfaces",
        "signing custody and security",
        "operations recovery",
      ],
    },
    nonceLedger: {
      purposes: [...REPORTING_NONCE_PURPOSES],
      fields: [...REPORTING_NONCE_FIELDS],
      uniqueBy: [...NONCE_UNIQUENESS_FIELDS],
      scopeExcludes: [...NONCE_SCOPE_EXCLUDED_FIELDS],
      allFieldsImmutable: true,
      reportingKeyIdNullability: {
        ...REPORTING_KEY_ID_NULLABILITY,
        requiredFor: [...REPORTING_KEY_ID_NULLABILITY.requiredFor],
      },
      signedWindowMs: { ...REPORTING_SIGNED_WINDOW_MS },
      registerRequiresNewReportingKeyId: true,
      rawTargetRule: "OPAQUE_EXACT_SIGNED_BYTES_NEVER_NORMALIZE_OR_RECONSTRUCT",
      invalidAuthBurnsNothing: true,
      authenticatedFailureRetainsBurn: [404, 409, 500, "handler_failure", "handler_crash"],
    },
    requestPipeline: {
      preBurnChecks: [...PRE_BURN_CHECKS],
      burnTransaction: [...BURN_TRANSACTION_STEPS],
      postBurnStages: [...POST_BURN_STAGES],
      shortTransactionEndsBeforeProtectedLookup: true,
      completedIdempotencyPrecedesProtectedLookup: true,
      changedFingerprintConflictsBeforeProtectedLookup: true,
    },
    lifecycle: {
      identityFields: [...REPORTING_KEY_IDENTITY_ALLOWED_FIELDS],
      headFields: [...REPORTING_LIFECYCLE_HEAD_FIELDS],
      eventFields: [...REPORTING_LIFECYCLE_EVENT_FIELDS],
      oneHeadBy: ["node_id", "implementer_id"],
      canonicalPreBootstrapHead: {
        epoch: 0,
        currentKeyId: null,
        priorKeyId: null,
        overlapExpiresAt: null,
        authHold: true,
        lifecycleEventId: null,
      },
      positiveEventEpoch: true,
      eventUniqueBy: [...REPORTING_LIFECYCLE_EVENT_UNIQUENESS_FIELDS],
      keyStates: [...REPORTING_KEY_STATES],
      eventTypes: [...REPORTING_LIFECYCLE_EVENT_TYPES],
      legalKeyTransitions: LEGAL_LIFECYCLE_KEY_TRANSITIONS.map((transition) => ({ ...transition })),
      eventsAppendOnly: true,
      identitiesImmutable: true,
      overlapWindowMs: REPORTING_KEY_OVERLAP_MS,
      overlapInterval: "SUCCESSOR_COMMIT_INCLUSIVE_TO_EXPIRY_EXCLUSIVE",
      transitionsUseSameHeadLock: [...REPORTING_LIFECYCLE_EVENT_TYPES],
      firstHeadLockCommitWins: true,
      lifecycleEventIsAuthoritative: true,
      headProjectionMustEqualCitedEvent: true,
      terminalKeysReactivate: false,
      occupiedPriorMustBeExplicitlyRetiredOrRevokedBeforeRotation: true,
      overlapExpiryDerivedFromSuccessorCommit: true,
      storedOverlapExpiryMustEqualDerivedExpiry: true,
      registrationEvidenceModes: [...REGISTRATION_EVIDENCE_MODES],
      registrationEvidenceFields: [...REGISTRATION_EVIDENCE_FIELDS],
      firstBootstrapEvidence: "AUTHENTICATED_CALLER_PLUS_NODE_APPROVAL_PLUS_PROOF_OF_POSSESSION",
      rotationEvidence: "EXISTING_KEY_ANCHOR_PLUS_PROOF_OF_POSSESSION",
      registrationCrossBinding: {
        exactNonceEvidenceFields: [
          "request_preimage_text", "request_preimage_sha256", "request_signature",
          "issued_at", "expires_at", "new_reporting_key_id",
        ],
        enrolmentMustExactlyMatchNonceEvidence: true,
        bootstrapEvidenceIdMustMatchCitedEvidence: true,
        bootstrapEvidenceNewKeyMustMatchRegisterPreimage: true,
        rotationAuthorizingKeyMatchesLedgerKey: true,
        rotationAuthorizingPreimageDigestAndSignatureMustExactlyMatch: true,
      },
      eventHashChain: { ...LIFECYCLE_EVENT_HASH_CHAIN },
    },
    mutationIdempotency: {
      fields: [...MUTATION_IDEMPOTENCY_FIELDS],
      uniqueBy: [...MUTATION_IDEMPOTENCY_UNIQUENESS_FIELDS],
      logicalFingerprintFields: [...LOGICAL_FINGERPRINT_FIELDS],
      logicalFingerprintExcludes: [...LOGICAL_FINGERPRINT_EXCLUDED_FIELDS],
      bodyDigestComparedOutsideKeyUniqueness: true,
      exactStatusAndResponseBytesCommitAtomicallyWithMutation: true,
      exactResponseBytesReplayAcrossKeyRotation: true,
      fingerprintGuardedRouteIds: [...FINGERPRINT_GUARDED_ROUTE_IDS],
      guardedFingerprintPartialUnique: {
        fields: [...GUARDED_FINGERPRINT_PARTIAL_UNIQUENESS.fields],
        whereRouteIdIn: [...GUARDED_FINGERPRINT_PARTIAL_UNIQUENESS.whereRouteIdIn],
      },
      fingerprintGuardDefeatsChangedUnsignedIdempotencyHeader: true,
      guardedDuplicateAuthorityFields: [...LOGICAL_FINGERPRINT_FIELDS],
      logicalFingerprintDerivedAuditOnly: true,
      idempotencyKey: { ...IDEMPOTENCY_KEY_CONTRACT },
      durablePendingRowsAllowed: MUTATION_IDEMPOTENCY_PERSISTENCE.durablePendingRowsAllowed,
      requiredCompletionFields: [...MUTATION_IDEMPOTENCY_PERSISTENCE.requiredCompletionFields],
      mutationAndCompletedResultAtomic:
        MUTATION_IDEMPOTENCY_PERSISTENCE.mutationAndCompletedResultAtomic,
      completedParentRequiresMatchingChild:
        MUTATION_IDEMPOTENCY_PERSISTENCE.completedParentRequiresMatchingChild,
      evidenceBindingFields: [...MUTATION_EVIDENCE_BINDING_FIELDS],
      nonceIdempotencyAndChildEvidenceMustMatch: true,
      routeRetention: MUTATION_ROUTE_RETENTION,
      immutability: { ...MUTATION_EVIDENCE_IMMUTABILITY },
      exactResponsePersistence: {
        statusRange: [100, 599],
        statusRequired: true,
        bodyRequired: true,
        completionTimestampRequired: true,
        bytesImmutableCopy: true,
        mutationAndResultCrashAtomic: true,
        replayReturnsFreshByteCopy: true,
      },
    },
    recovery: {
      backupIncludesAllEvidence: true,
      regressionMarkers: ["lifecycle_epoch", "nonce_burn_high_water"],
      restorePolicy: {
        ...RESTORE_POLICY,
        releaseRequires: [...RESTORE_POLICY.releaseRequires],
      },
      restoreAdmissionRequiresBothHoldsClear: ["node_restore_hold", "lifecycle_head_auth_hold"],
      retention: { ...REPORTING_RETENTION },
    },
    custody: {
      allowedIdentityFields: [...REPORTING_KEY_IDENTITY_ALLOWED_FIELDS],
      forbiddenIdentityFields: [...REPORTING_KEY_IDENTITY_FORBIDDEN_FIELDS],
      nodeStoresReportingPublicKeyOnly: true,
      exactFieldSetRequired: true,
      unknownFieldsRejected: true,
    },
    scopeExclusions: [
      "physical_application_migration", "legacy_push_reporting_tables",
      "frozen_v1_path_changes", "private_key_storage", "live_action",
    ],
  } as const;
}

export type ReportingPersistenceManifest = ReturnType<typeof buildReportingPersistenceManifest>;
