// Suite-tuple goldens, transcribed VERBATIM from the canonical-fields byte authority
// (the A.8.2 preimage lines plus the pinned digest/signature table). These are the independent capture the serializer must
// reproduce; nothing here is generated by the code under test. Each `preimageText` is the exact
// A.8.2 line (the `\n` is one real LF; no trailing newline). Each `sha256` and `signature` is the
// A.8 pinned value. `seedByte` is the A.8 deterministic Ed25519 seed (32 repeated bytes) of the
// signer's key class; a golden with `seedByte: null` is unsigned (A.7 fingerprint).

export interface SuiteGoldenVector {
  readonly id: string;
  readonly purpose: string;
  readonly values: Readonly<Record<string, unknown>>;
  readonly preimageText: string;
  readonly sha256: string;
  readonly seedByte: number | null;
  readonly signature: string | null;
}

// A.8 fixture identifiers (lines 412–424) and role public keys (lines 402–408).
const NODE_ID = "11111111-1111-4111-8111-111111111111";
const IMPLEMENTER_ID = "22222222-2222-4222-8222-222222222222";
const OPERATION_ID = "33333333-3333-4333-8333-333333333333";
const DESTINATION_WALLET_ID = "44444444-4444-4444-8444-444444444444";
const SOURCE_WALLET = "55555555-5555-4555-8555-555555555555";
const DESTINATION_ID = "66666666-6666-4666-8666-666666666666";
const NONCE = "99999999-9999-4999-8999-999999999999";
const DEVICE_KEY_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const EVENT_ID = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const EVENT_ID_B = "dddddddd-dddd-4ddd-8ddd-dddddddddddd";
const REPORTING_KEY_ID = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";

const DEVICE_PUBKEY = "iojj3XQJ8ZX9UtstPLpdcspnCb8dlBIb83SIAbQPb1w="; // seed 01
const SENDER_PUBKEY = "gTl3Dqh9F19Wo1Rmw0x-zMuNipG07jeiXfYPW4_Js5Q="; // seed 02
const RECEIVER_PUBKEY = "7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E="; // seed 03
const REPORTING_PUBKEY = "ypOsFwUYcHHWe4PH_w7-gQjo7EUwV113JoeTM9vavnw="; // seed 04

const ZEROS_64 = "0".repeat(64);
const BODY_SHA256 = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"; // SHA-256 of "{}"
// SHA-256 of the exact stored bytes of the encoded receive-code fixture
// `packages/generic-node-contracts/goldens/transfer-code/receive-code.v1.b64url.txt`, hashed
// as-stored. The earlier illustrative placeholder `4b3e384d…` (= SHA-256("golden-transfer-code-v1"))
// is VOID for this artifact and MUST NOT be accepted. A.8.1's SplitChain golden keeps its own
// `4b3e384d…` line — a separate construct this row deliberately does not touch.
const TRANSFER_CODE_SHA256 = "104eb00c3bda958b82b7ce5a24e582dd9efa3e63d2192838fe26b5b23dcb2bab";
const INNER_SHA256 = "ce0741df9ed652b25d0294746c67acd6d9ecb4e3318c3691582fc2acdd52be51";
const EVENT_A_HASH = "1f0ec14dd26b58d3ce4200a18125080951b0e391c6ec081f71b8c49d44b8f4be";
const S_SIGNATURE = "uP0HeCG-ZT1svQK-drwexhc1mrxx4QLBdfgFlw8nqRrwwvcJcPazgcPxp8aMdz7iJricO75II0bUzvwlBUUDDw==";
const STEP_1_SIGNATURE = "wpAPEHD-wRRyfdoLM5FUgwS5OhCVwkQBV5w-XFDSx_VK19QiW5szD6Cuy1ogiNlIlvWtx4LlZPIdAm81eKX0BA==";

// Signer seed bytes (A.8 line 402–408): 00 node identity/event, 01 device, 04 reporting.
const SEED_NODE = 0x00;
const SEED_DEVICE = 0x01;
const SEED_REPORTING = 0x04;

export const SUITE_GOLDENS: readonly SuiteGoldenVector[] = [
  {
    id: "receive-expected",
    purpose: "zp-receive-expected-v1",
    values: {
      purpose: "zp-receive-expected-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      implementer_id: IMPLEMENTER_ID,
      operation_id: OPERATION_ID,
      receiver_wallet_id: SOURCE_WALLET,
      receiver_pubkey: RECEIVER_PUBKEY,
      amount_zkz: "2.25",
      discriminator: OPERATION_ID,
      anchor: "ord_7YQ3",
      receiver_t0_fingerprint: ZEROS_64,
      expiry_unix_time_secs: "1784336400",
      after_landing: { kind: "HOLD", destination_id: null },
      transfer_code_sha256: TRANSFER_CODE_SHA256,
    },
    preimageText:
      'zp-receive-expected-v1\n{"purpose":"zp-receive-expected-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","implementer_id":"22222222-2222-4222-8222-222222222222","operation_id":"33333333-3333-4333-8333-333333333333","receiver_wallet_id":"55555555-5555-4555-8555-555555555555","receiver_pubkey":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","amount_zkz":"2.25","discriminator":"33333333-3333-4333-8333-333333333333","anchor":"ord_7YQ3","receiver_t0_fingerprint":"0000000000000000000000000000000000000000000000000000000000000000","expiry_unix_time_secs":"1784336400","after_landing":{"kind":"HOLD","destination_id":null},"transfer_code_sha256":"104eb00c3bda958b82b7ce5a24e582dd9efa3e63d2192838fe26b5b23dcb2bab"}',
    sha256: "f49635f02d8de86c5b4324f13520cc38c094d79ee2c0df5df60547c590ede498",
    seedByte: SEED_NODE,
    signature: "3NKuFfWanImIVOPKDN9RBv2pUSwsZ6tYypaYyEN_c4z4Zl-TCIC9_y4q5GEM8SYaSWMMgJBa15-UpsXh_9dBBQ==",
  },
  {
    id: "move-internal-expected",
    purpose: "zp-move-internal-expected-v1",
    values: {
      purpose: "zp-move-internal-expected-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      implementer_id: IMPLEMENTER_ID,
      operation_id: OPERATION_ID,
      source_wallet_id: SOURCE_WALLET,
      source_pubkey: SENDER_PUBKEY,
      destination_id: DESTINATION_ID,
      destination_wallet_id: DESTINATION_WALLET_ID,
      destination_pubkey: RECEIVER_PUBKEY,
      amount_zkz: "2.25",
      spawned_from_operation_id: null,
      references_operation_id: null,
    },
    preimageText:
      'zp-move-internal-expected-v1\n{"purpose":"zp-move-internal-expected-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","implementer_id":"22222222-2222-4222-8222-222222222222","operation_id":"33333333-3333-4333-8333-333333333333","source_wallet_id":"55555555-5555-4555-8555-555555555555","source_pubkey":"gTl3Dqh9F19Wo1Rmw0x-zMuNipG07jeiXfYPW4_Js5Q=","destination_id":"66666666-6666-4666-8666-666666666666","destination_wallet_id":"44444444-4444-4444-8444-444444444444","destination_pubkey":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","amount_zkz":"2.25","spawned_from_operation_id":null,"references_operation_id":null}',
    sha256: "ad964723e07ca2aef3356f1e02990e07b90be49b5387a7095091398a10944a14",
    seedByte: SEED_NODE,
    signature: "LBOpWe9v6yQXGYeerr0oIoW6gm3kF-nga7FrHkANO7jEw3XjkKjqqPYeCshORWQnXMU9kkKV_0-eE_FLmNUpDA==",
  },
  {
    id: "send-external-expected",
    purpose: "zp-send-external-expected-v1",
    values: {
      purpose: "zp-send-external-expected-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      implementer_id: IMPLEMENTER_ID,
      operation_id: OPERATION_ID,
      source_selector: { kind: "WALLET_ID", wallet_id: SOURCE_WALLET },
      source_pubkey: SENDER_PUBKEY,
      destination_address: RECEIVER_PUBKEY,
      amount_zkz: "2.25",
      references_operation_id: null,
    },
    preimageText:
      'zp-send-external-expected-v1\n{"purpose":"zp-send-external-expected-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","implementer_id":"22222222-2222-4222-8222-222222222222","operation_id":"33333333-3333-4333-8333-333333333333","source_selector":{"kind":"WALLET_ID","wallet_id":"55555555-5555-4555-8555-555555555555"},"source_pubkey":"gTl3Dqh9F19Wo1Rmw0x-zMuNipG07jeiXfYPW4_Js5Q=","destination_address":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","amount_zkz":"2.25","references_operation_id":null}',
    sha256: "f094f981f833c908fae1fa661cb6d9f6c3cdf29bab792f2660b866c588f22cb5",
    seedByte: SEED_NODE,
    signature: "TKbgi1fVDCnik1TscotEf0i8eFp3NuQ3JlSsPMJgy6imF-Nct9KniWMkPv5bUAtDNp7fFXG89YLI5qme6MyWDA==",
  },
  {
    id: "send-external-approval",
    purpose: "zp-send-external-approval-v1",
    values: {
      purpose: "zp-send-external-approval-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      operation_id: OPERATION_ID,
      source_selector: { kind: "WALLET_ID", wallet_id: SOURCE_WALLET },
      source_pubkey: SENDER_PUBKEY,
      destination_address: RECEIVER_PUBKEY,
      amount_zkz: "2.25",
      references_operation_id: null,
      nonce: NONCE,
      issued_at: "2026-07-18T00:00:00.000Z",
      expires_at: "2026-07-18T00:05:00.000Z",
    },
    preimageText:
      'zp-send-external-approval-v1\n{"purpose":"zp-send-external-approval-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","operation_id":"33333333-3333-4333-8333-333333333333","source_selector":{"kind":"WALLET_ID","wallet_id":"55555555-5555-4555-8555-555555555555"},"source_pubkey":"gTl3Dqh9F19Wo1Rmw0x-zMuNipG07jeiXfYPW4_Js5Q=","destination_address":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","amount_zkz":"2.25","references_operation_id":null,"nonce":"99999999-9999-4999-8999-999999999999","issued_at":"2026-07-18T00:00:00.000Z","expires_at":"2026-07-18T00:05:00.000Z"}',
    sha256: "d7c03561bd9bc87e302c533f03741c34d44058fc0aaf1b59b17a4f28f8022146",
    seedByte: SEED_DEVICE,
    signature: "HLd6EN7uw2KHCgRAryuyEh6ljmHsjgvCJ6Ke1Gq3fb0PDV1Vsn3QCzuo51o0VnH9LCbDI3c_s6AFK3NO013ZCA==",
  },
  {
    id: "destination-bless",
    purpose: "zp-destination-bless-v1",
    values: {
      purpose: "zp-destination-bless-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      destination_id: DESTINATION_ID,
      wallet_id: DESTINATION_WALLET_ID,
      wallet_pubkey: RECEIVER_PUBKEY,
      nonce: NONCE,
      issued_at: "2026-07-18T00:00:00.000Z",
      expires_at: "2026-07-18T00:05:00.000Z",
    },
    preimageText:
      'zp-destination-bless-v1\n{"purpose":"zp-destination-bless-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","destination_id":"66666666-6666-4666-8666-666666666666","wallet_id":"44444444-4444-4444-8444-444444444444","wallet_pubkey":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","nonce":"99999999-9999-4999-8999-999999999999","issued_at":"2026-07-18T00:00:00.000Z","expires_at":"2026-07-18T00:05:00.000Z"}',
    sha256: "9f9b0f61d152037f7d470bed2803e39b22b3f9830cf60f608f4b92c1f294fc70",
    seedByte: SEED_DEVICE,
    signature: "W490dwQEKHVOCP2npX1QABoGNwDALJ9KqijN7D-yu9b4GRsScdJEcqtOoKq1z0f2EP0Rf5MOaKu9I6hplLa8BQ==",
  },
  {
    id: "device-enrol",
    purpose: "zp-device-enrol-v1",
    values: {
      purpose: "zp-device-enrol-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      new_device_key_id: DEVICE_KEY_ID,
      new_device_public_key: DEVICE_PUBKEY,
      label: "golden-device",
      nonce: NONCE,
      issued_at: "2026-07-18T00:00:00.000Z",
      expires_at: "2026-07-18T00:05:00.000Z",
    },
    preimageText:
      'zp-device-enrol-v1\n{"purpose":"zp-device-enrol-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","new_device_key_id":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","new_device_public_key":"iojj3XQJ8ZX9UtstPLpdcspnCb8dlBIb83SIAbQPb1w=","label":"golden-device","nonce":"99999999-9999-4999-8999-999999999999","issued_at":"2026-07-18T00:00:00.000Z","expires_at":"2026-07-18T00:05:00.000Z"}',
    sha256: "64e6a3213325f01253954b27abeb4ace733c6f57d0cbc888e5f3bd438b789dc9",
    seedByte: SEED_DEVICE,
    signature: "wW3OFAKEAmF93BfX2m8GkovUBIJUVz_2G6pXuTJMy5CR3xqBoaTo7UrPQjBvqErxqa9CgF5NCBo3GztayvawCw==",
  },
  {
    id: "report-request",
    purpose: "zp-report-request-v1",
    values: {
      purpose: "zp-report-request-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      implementer_id: IMPLEMENTER_ID,
      method: "POST",
      path: "/v1/operations/33333333-3333-4333-8333-333333333333/verification-complete",
      body_sha256: BODY_SHA256,
      nonce: NONCE,
      issued_at: "2026-07-18T00:00:00.000Z",
      expires_at: "2026-07-18T00:01:00.000Z",
    },
    preimageText:
      'zp-report-request-v1\n{"purpose":"zp-report-request-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","implementer_id":"22222222-2222-4222-8222-222222222222","method":"POST","path":"/v1/operations/33333333-3333-4333-8333-333333333333/verification-complete","body_sha256":"44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a","nonce":"99999999-9999-4999-8999-999999999999","issued_at":"2026-07-18T00:00:00.000Z","expires_at":"2026-07-18T00:01:00.000Z"}',
    sha256: "31a0edb52dea2b193bd56add32363b7afba1021c5f9820b8c2ee3ea263cfc463",
    seedByte: SEED_REPORTING,
    signature: "Drt5bF_T8OWPyJuth1w6rB-dS0rNBhoh_msFgW8lZiY25FzXiuzeSbKU4x8mA5Et2aIrjBa8dlRGPV6GNF3yAw==",
  },
  {
    id: "reporting-register",
    purpose: "zp-reporting-register-v1",
    values: {
      purpose: "zp-reporting-register-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      implementer_id: IMPLEMENTER_ID,
      new_reporting_key_id: REPORTING_KEY_ID,
      new_reporting_public_key: REPORTING_PUBKEY,
      supersedes_key_id: null,
      nonce: NONCE,
      issued_at: "2026-07-18T00:00:00.000Z",
      expires_at: "2026-07-18T00:05:00.000Z",
    },
    preimageText:
      'zp-reporting-register-v1\n{"purpose":"zp-reporting-register-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","implementer_id":"22222222-2222-4222-8222-222222222222","new_reporting_key_id":"cccccccc-cccc-4ccc-8ccc-cccccccccccc","new_reporting_public_key":"ypOsFwUYcHHWe4PH_w7-gQjo7EUwV113JoeTM9vavnw=","supersedes_key_id":null,"nonce":"99999999-9999-4999-8999-999999999999","issued_at":"2026-07-18T00:00:00.000Z","expires_at":"2026-07-18T00:05:00.000Z"}',
    sha256: "98fba788ad4ba2141dc400f1cd0f58db3a03b34a00b5a04ecdcfe239e9912e7e",
    seedByte: SEED_REPORTING,
    signature: "mSzq0luyM9AubD8PrVDBeoSwljM8SGXmUTsXVhVaLJiX0bPQgHKzFwBwIDkGTpm-2CdsINIQObzjOvHvCMCuDA==",
  },
  {
    id: "node-event-a",
    purpose: "zp-node-event-v1",
    values: {
      purpose: "zp-node-event-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      event_id: EVENT_ID,
      seq: "1",
      operation_id: OPERATION_ID,
      wallet_id: SOURCE_WALLET,
      event_type: "receive.ready",
      data_sha256: BODY_SHA256,
      previous_event_hash: null,
      created_at: "2026-07-18T00:00:00.000Z",
    },
    preimageText:
      'zp-node-event-v1\n{"purpose":"zp-node-event-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","event_id":"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb","seq":"1","operation_id":"33333333-3333-4333-8333-333333333333","wallet_id":"55555555-5555-4555-8555-555555555555","event_type":"receive.ready","data_sha256":"44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a","previous_event_hash":null,"created_at":"2026-07-18T00:00:00.000Z"}',
    sha256: "9644a48d9f0a988c62321a371ad66f993ae4f428ae3a3ee48d0dc290e0560226",
    seedByte: SEED_NODE,
    signature: "AQPu22VB5jB8nGjtSmbT_U1AN0yvswxFt2nTxD38xeEWgF_n43g-i23l5nMy0u9tBRWaYStxzjNdyllvwXGxDg==",
  },
  {
    id: "node-event-b",
    purpose: "zp-node-event-v1",
    values: {
      purpose: "zp-node-event-v1",
      canonical_version: 1,
      node_id: NODE_ID,
      event_id: EVENT_ID_B,
      seq: "2",
      operation_id: OPERATION_ID,
      wallet_id: null,
      event_type: "operation.needs_attention",
      data_sha256: BODY_SHA256,
      previous_event_hash: EVENT_A_HASH,
      created_at: "2026-07-18T00:00:01.000Z",
    },
    preimageText:
      'zp-node-event-v1\n{"purpose":"zp-node-event-v1","canonical_version":1,"node_id":"11111111-1111-4111-8111-111111111111","event_id":"dddddddd-dddd-4ddd-8ddd-dddddddddddd","seq":"2","operation_id":"33333333-3333-4333-8333-333333333333","wallet_id":null,"event_type":"operation.needs_attention","data_sha256":"44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a","previous_event_hash":"1f0ec14dd26b58d3ce4200a18125080951b0e391c6ec081f71b8c49d44b8f4be","created_at":"2026-07-18T00:00:01.000Z"}',
    sha256: "42c27944165f242f2c4fc276ff369da58ed6055ffd71c2788f1f6fe73aec2e2c",
    seedByte: SEED_NODE,
    signature: "lYyU11UCfQMvAS5KMMZKU9Cg6_Qvo6HbcLNz_ulD0WuBNWherIa3iLZeEiNla-gkx1qNsyDtGYJNHIpqeHSdCg==",
  },
  {
    id: "wallet-head-fingerprint",
    purpose: "zp-wallet-head-fingerprint-v1",
    values: {
      purpose: "zp-wallet-head-fingerprint-v1",
      canonical_version: 1,
      wallet_public_key: RECEIVER_PUBKEY,
      state_kind: "HEAD",
      s_signature: S_SIGNATURE,
      p_signature: "",
      b_amount: "2.25",
      inner_sha256: INNER_SHA256,
      step_1_signature: STEP_1_SIGNATURE,
      step_2_signature: S_SIGNATURE,
    },
    preimageText:
      'zp-wallet-head-fingerprint-v1\n{"purpose":"zp-wallet-head-fingerprint-v1","canonical_version":1,"wallet_public_key":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","state_kind":"HEAD","s_signature":"uP0HeCG-ZT1svQK-drwexhc1mrxx4QLBdfgFlw8nqRrwwvcJcPazgcPxp8aMdz7iJricO75II0bUzvwlBUUDDw==","p_signature":"","b_amount":"2.25","inner_sha256":"ce0741df9ed652b25d0294746c67acd6d9ecb4e3318c3691582fc2acdd52be51","step_1_signature":"wpAPEHD-wRRyfdoLM5FUgwS5OhCVwkQBV5w-XFDSx_VK19QiW5szD6Cuy1ogiNlIlvWtx4LlZPIdAm81eKX0BA==","step_2_signature":"uP0HeCG-ZT1svQK-drwexhc1mrxx4QLBdfgFlw8nqRrwwvcJcPazgcPxp8aMdz7iJricO75II0bUzvwlBUUDDw=="}',
    sha256: "d03a98b770684e577667f9bde01276b196b98db31663f23b0900623d6dffca2a",
    seedByte: null,
    signature: null,
  },
  // The A.7 `state_kind` GENESIS variant, published at A.8.2 alongside the HEAD line.
  // Same receiver wallet (seed 03) one state earlier: no prior settled transaction, so the frozen
  // genesis vocabulary applies (`GENESIS_FINGERPRINT_VALUES`): S=P="" and B="0", with
  // inner_sha256 / step_1_signature / step_2_signature all JSON null — never omitted, never "".
  // This is the byte fixture A.9 negative vector 1 (omitted-instead-of-null) tests against.
  {
    id: "wallet-head-fingerprint-genesis",
    purpose: "zp-wallet-head-fingerprint-v1",
    values: {
      purpose: "zp-wallet-head-fingerprint-v1",
      canonical_version: 1,
      wallet_public_key: RECEIVER_PUBKEY,
      state_kind: "GENESIS",
      s_signature: "",
      p_signature: "",
      b_amount: "0",
      inner_sha256: null,
      step_1_signature: null,
      step_2_signature: null,
    },
    preimageText:
      'zp-wallet-head-fingerprint-v1\n{"purpose":"zp-wallet-head-fingerprint-v1","canonical_version":1,"wallet_public_key":"7UkoxijRwsbq6QM4kFmVYSlZJzpcY_k2NsFGFKyHN9E=","state_kind":"GENESIS","s_signature":"","p_signature":"","b_amount":"0","inner_sha256":null,"step_1_signature":null,"step_2_signature":null}',
    sha256: "cb22b244558305b5d3cac27b59546806dbb5a135e049ae2fe155805ab5e951bd",
    seedByte: null,
    signature: null,
  },
];
