import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * Amounts vectors (the amounts concern and its downstream consumers) — unsigned frozen vector JSON in the unsigned-evidence class
 * (raw bytes retained and authenticated by digest, not by a signature). String amounts with
 * ROUND_DOWN semantics throughout; no float appears in any vector.
 */
const AMOUNTS_CAPTURE_METHOD =
  "Hand-authored vector table frozen as contract under the amounts freeze; " +
  "string-amount decimal grammar with ROUND_DOWN rounding, arbitrary-precision semantics, no floats";

const AMOUNTS_WALLET_VERSION = "n/a — frozen vector table; no wallet capture";

const AMOUNTS_KEY_MATERIAL = "none — pure decimal string vectors";

const AMOUNTS_SPEC_CITATIONS = [
  "zkz-amount-grammar (amount grammar, ROUND_DOWN)",
  "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
] as const;

const AMOUNTS_DECISION_REFS = [
  "zkz-amount-grammar",
  "amount-bounds-authority-split",
  "amount-column-precision-widening",
] as const;

export const AMOUNTS_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "amounts/arithmetic.vectors",
    byteClass: "unsigned-evidence",
    indexPath: "src/amounts/__vectors__/arithmetic.vectors.json",
    files: [
      { path: "src/amounts/__vectors__/arithmetic.vectors.json", sha256: "d4fd6df701b4ce89c243c95c6a30d079cb032ebb5ad0eaa99193f53513b7b912" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod: AMOUNTS_CAPTURE_METHOD,
      captureDate: "2026-07-19",
      walletVersion: AMOUNTS_WALLET_VERSION,
      source: "packages/generic-node-contracts/src/amounts (the frozen amounts contract)",
      keyMaterial: AMOUNTS_KEY_MATERIAL,
      specCitations: AMOUNTS_SPEC_CITATIONS,
      decisionRefs: AMOUNTS_DECISION_REFS,
    },
  },
  {
    fixtureId: "amounts/boundary.vectors",
    byteClass: "unsigned-evidence",
    indexPath: "src/amounts/__vectors__/boundary.vectors.json",
    files: [
      { path: "src/amounts/__vectors__/boundary.vectors.json", sha256: "c07dcc7e71b93aa8035876a64d71da75b454c48ca875a7c4401bce4fb89f379c" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod: AMOUNTS_CAPTURE_METHOD,
      captureDate: "2026-07-19",
      walletVersion: AMOUNTS_WALLET_VERSION,
      source: "packages/generic-node-contracts/src/amounts (the frozen amounts contract)",
      keyMaterial: AMOUNTS_KEY_MATERIAL,
      specCitations: AMOUNTS_SPEC_CITATIONS,
      decisionRefs: AMOUNTS_DECISION_REFS,
    },
  },
  {
    fixtureId: "amounts/emission.vectors",
    byteClass: "unsigned-evidence",
    indexPath: "src/amounts/__vectors__/emission.vectors.json",
    files: [
      { path: "src/amounts/__vectors__/emission.vectors.json", sha256: "2f42b0a53a6a0425d5b2401cf98a8909bee545da65c3022b747bd45c528a0bd5" },
      { path: "src/amounts/__vectors__/emission.golden.json", sha256: "76d1ec5fda143cc12c22f10486335eae9b1e899d62ac1db9895d1dd3cb5f218d" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod: AMOUNTS_CAPTURE_METHOD,
      captureDate: "2026-07-19",
      walletVersion: AMOUNTS_WALLET_VERSION,
      source: "packages/generic-node-contracts/src/amounts (the frozen amounts contract)",
      keyMaterial: AMOUNTS_KEY_MATERIAL,
      specCitations: AMOUNTS_SPEC_CITATIONS,
      decisionRefs: AMOUNTS_DECISION_REFS,
      details: {
        sibling_golden: "emission.golden.json — canonical-form emission golden covered by this record's digest set",
      },
    },
  },
];
