import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * the approval concern approval goldens — a suite canonical tuple (the `zp-send-external-approval-v1`
 * purpose). Provenance generalizes the sibling `*.meta.json` sidecar; the constructor chain
 * (the named concern/the named concern) is referenced by provenance record only, never imported.
 */
export const APPROVAL_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "approval/zp-send-external-approval-v1",
    byteClass: "suite-tuple",
    indexPath: "goldens/approval/zp-send-external-approval-v1.meta.json",
    files: [
      { path: "goldens/approval/zp-send-external-approval-v1.meta.json", sha256: "1c483493c4f3c6dc99b9df5a0f637f039ea508816447c6db3571f5ee7fa4864c" },
      { path: "goldens/approval/zp-send-external-approval-v1.preimage.txt", sha256: "d7c03561bd9bc87e302c533f03741c34d44058fc0aaf1b59b17a4f28f8022146" },
      { path: "goldens/approval/zp-send-external-approval-v1.digest.hex", sha256: "b8a162f4b807402a1c74443fdc113b874b517be527f726714cae883ea3d34e3b" },
      { path: "goldens/approval/zp-send-external-approval-v1.sig.b64", sha256: "a112a12ce9b9187eb9e75e7404c76ee4da67eb5e24a9ae6adfe43a3f082c86e3" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod:
        "Machine-generated by the canonical constructor: domain-separated canonical serializer preimage " +
        "(purpose + LF + JSON.stringify(payload)) per the canonical-fields preimage encoding, detached Ed25519 signature over the exact " +
        "preimage bytes (padded base64url), frozen as committed goldens; the optional additive " +
        "device-key signature signs this tuple while the mandatory approval gate is fresh TOTP, which never signs bytes",
      captureDate: "2026-07-20",
      walletVersion: "n/a — canonical constructor output; no wallet capture",
      source:
        "canonical-fields reference: approval tuple schema (schema fields), " +
        "domain-separated preimage encoding, and the expected machine-generated outputs table",
      keyMaterial:
        "deterministic test-only Ed25519 device key (32-byte seed filled with 0x01); MUST never be used with live ZKZ",
      specCitations: [
        "canonical-fields reference: approval tuple schema",
        "canonical-fields reference: domain-separated preimage encoding",
        "protocol foundation: suite canonical tuple byte class",
        "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
      ],
      decisionRefs: ["single-approval-single-sign-rule"],
      details: {
        artifact: "zp-send-external-approval-v1",
        signing_role: "device",
        artifact_digest_sha256: "d7c03561bd9bc87e302c533f03741c34d44058fc0aaf1b59b17a4f28f8022146",
        verification_pubkey_b64: "iojj3XQJ8ZX9UtstPLpdcspnCb8dlBIb83SIAbQPb1w=",
        constructor_refs:
          "the SplitChain v2 constructors and the canonical suite-tuple module — " +
          "referenced by provenance record only; not imported",
      },
    },
  },
];
