import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * the artifacts concern expected-artifact goldens — suite canonical tuples (the frozen `zp-*-expected-v1`
 * signed surfaces of the artifacts freeze) plus the pinned deterministic node-identity verification key. The key
 * file is unsigned raw bytes pinned by digest, so it carries the `unsigned-evidence` class.
 */
const EXPECTED_ARTIFACT_CAPTURE_METHOD =
  "Machine-generated by the canonical constructor: domain-separated canonical serializer preimage " +
  "(purpose + LF + JSON.stringify(payload)) per the canonical-fields preimage encoding, detached Ed25519 signature over the exact " +
  "preimage bytes by the deterministic test node key (padded base64url), frozen as committed goldens";

const EXPECTED_ARTIFACT_WALLET_VERSION = "n/a — canonical constructor output; no wallet capture";

const EXPECTED_ARTIFACT_KEY_MATERIAL =
  "deterministic test-only Ed25519 node identity key (32-byte seed filled with 0x00); MUST never be used with live ZKZ";

const EXPECTED_ARTIFACT_CONSTRUCTOR_REFS =
  "the SplitChain v2 constructors and the canonical suite-tuple module — " +
  "referenced by provenance record only; not imported";

const expectedArtifactSpecCitations = (schemaSection: string): readonly string[] => [
  `canonical-fields reference: ${schemaSection} tuple schema`,
  "canonical-fields reference: domain-separated preimage encoding",
  "protocol foundation: suite canonical tuple byte class",
  "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
];

const expectedArtifactSource = (schemaSection: string): string =>
  `canonical-fields reference: ${schemaSection} tuple schema (schema fields), ` +
  "domain-separated preimage encoding, and the expected machine-generated outputs table";

export const ARTIFACTS_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "artifacts/node-identity.pub",
    byteClass: "unsigned-evidence",
    indexPath: "goldens/artifacts/node-identity.pub.meta.json",
    files: [
      { path: "goldens/artifacts/node-identity.pub.meta.json", sha256: "6be340f2438c35924a10b76b66cdc9eb8d1f28ee81be8a059dc797c3e14b2256" },
      { path: "goldens/artifacts/node-identity.pub.b64", sha256: "8eb7cca2ecabb7fb12e9d6f356ff4c204c64cb94f0db87b0ccad4649f69c7de0" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod:
        "Deterministic test key derivation (32-byte Ed25519 seed filled with 0x00); the raw public " +
        "key bytes are pinned unpadded-base64 and authenticated by digest only — a pinned verification key is not a signed blob",
      captureDate: "2026-07-20",
      walletVersion: EXPECTED_ARTIFACT_WALLET_VERSION,
      source:
        "canonical-fields reference: deterministic test key material (node identity row)",
      keyMaterial: EXPECTED_ARTIFACT_KEY_MATERIAL,
      specCitations: [
        "canonical-fields reference: deterministic test key material and expected outputs",
        "protocol foundation: unsigned-evidence byte class",
        "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
      ],
      decisionRefs: ["expected-artifact-surfaces-freeze"],
      details: {
        role: "node",
        public_key_b64: "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=",
      },
    },
  },
  {
    fixtureId: "artifacts/zp-move-internal-expected-v1",
    byteClass: "suite-tuple",
    indexPath: "goldens/artifacts/zp-move-internal-expected-v1.meta.json",
    files: [
      { path: "goldens/artifacts/zp-move-internal-expected-v1.meta.json", sha256: "ba76776279b139eb573a04a4b30ced07f4a14f7160e25aebaaa2986faa426f9e" },
      { path: "goldens/artifacts/zp-move-internal-expected-v1.preimage.txt", sha256: "ad964723e07ca2aef3356f1e02990e07b90be49b5387a7095091398a10944a14" },
      { path: "goldens/artifacts/zp-move-internal-expected-v1.digest.hex", sha256: "cdb975c40bd68f9585b3285c403585fbebb73551638faa668ea78259636b0472" },
      { path: "goldens/artifacts/zp-move-internal-expected-v1.sig.b64", sha256: "62b5fcccdc4d7d17ee48a9e416bca4f64db5d62b9d482c026134db98eb8bf0d0" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod: EXPECTED_ARTIFACT_CAPTURE_METHOD,
      captureDate: "2026-07-20",
      walletVersion: EXPECTED_ARTIFACT_WALLET_VERSION,
      source: expectedArtifactSource("zp-move-internal-expected-v1"),
      keyMaterial: EXPECTED_ARTIFACT_KEY_MATERIAL,
      specCitations: expectedArtifactSpecCitations("zp-move-internal-expected-v1"),
      decisionRefs: ["expected-artifact-surfaces-freeze"],
      details: {
        artifact: "zp-move-internal-expected-v1",
        signing_role: "node",
        artifact_digest_sha256: "ad964723e07ca2aef3356f1e02990e07b90be49b5387a7095091398a10944a14",
        verification_pubkey_b64: "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=",
        constructor_refs: EXPECTED_ARTIFACT_CONSTRUCTOR_REFS,
      },
    },
  },
  {
    fixtureId: "artifacts/zp-receive-expected-v1",
    byteClass: "suite-tuple",
    indexPath: "goldens/artifacts/zp-receive-expected-v1.meta.json",
    files: [
      { path: "goldens/artifacts/zp-receive-expected-v1.meta.json", sha256: "c099eb9b9bcece9b49bab65cd8929729a905d9d9d3a3eb2a76038c49cc7ce8cb" },
      { path: "goldens/artifacts/zp-receive-expected-v1.preimage.txt", sha256: "f49635f02d8de86c5b4324f13520cc38c094d79ee2c0df5df60547c590ede498" },
      { path: "goldens/artifacts/zp-receive-expected-v1.digest.hex", sha256: "8d2380efddc58bc1cf1ed40d4c2cd6421604618e8aee5f65b5d973245e7ca9cb" },
      { path: "goldens/artifacts/zp-receive-expected-v1.sig.b64", sha256: "513c9c00d0deeae6597e60f144de3ad3944de80aabeebdbb3f4f5604abeabbc4" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod: EXPECTED_ARTIFACT_CAPTURE_METHOD,
      captureDate: "2026-07-20",
      walletVersion: EXPECTED_ARTIFACT_WALLET_VERSION,
      source: expectedArtifactSource("zp-receive-expected-v1"),
      keyMaterial: EXPECTED_ARTIFACT_KEY_MATERIAL,
      specCitations: expectedArtifactSpecCitations("zp-receive-expected-v1"),
      decisionRefs: ["expected-artifact-surfaces-freeze"],
      details: {
        artifact: "zp-receive-expected-v1",
        signing_role: "node",
        artifact_digest_sha256: "f49635f02d8de86c5b4324f13520cc38c094d79ee2c0df5df60547c590ede498",
        verification_pubkey_b64: "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=",
        constructor_refs: EXPECTED_ARTIFACT_CONSTRUCTOR_REFS,
      },
    },
  },
  {
    fixtureId: "artifacts/zp-send-external-expected-v1",
    byteClass: "suite-tuple",
    indexPath: "goldens/artifacts/zp-send-external-expected-v1.meta.json",
    files: [
      { path: "goldens/artifacts/zp-send-external-expected-v1.meta.json", sha256: "4fe09574595701fbeabcff0de099a077d6c0af7deb176216d8e7e705d70ab22f" },
      { path: "goldens/artifacts/zp-send-external-expected-v1.preimage.txt", sha256: "f094f981f833c908fae1fa661cb6d9f6c3cdf29bab792f2660b866c588f22cb5" },
      { path: "goldens/artifacts/zp-send-external-expected-v1.digest.hex", sha256: "3bbed6945721e4cd33a1f17ed9e920ad0941a333c221e33b8655e25004d35af6" },
      { path: "goldens/artifacts/zp-send-external-expected-v1.sig.b64", sha256: "b08f34d7ece5a11c12bca40c392f9c529c8699be2969b18002843b73a03ab343" },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod: EXPECTED_ARTIFACT_CAPTURE_METHOD,
      captureDate: "2026-07-20",
      walletVersion: EXPECTED_ARTIFACT_WALLET_VERSION,
      source: expectedArtifactSource("zp-send-external-expected-v1"),
      keyMaterial: EXPECTED_ARTIFACT_KEY_MATERIAL,
      specCitations: expectedArtifactSpecCitations("zp-send-external-expected-v1"),
      decisionRefs: ["expected-artifact-surfaces-freeze"],
      details: {
        artifact: "zp-send-external-expected-v1",
        signing_role: "node",
        artifact_digest_sha256: "f094f981f833c908fae1fa661cb6d9f6c3cdf29bab792f2660b866c588f22cb5",
        verification_pubkey_b64: "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=",
        constructor_refs: EXPECTED_ARTIFACT_CONSTRUCTOR_REFS,
      },
    },
  },
];
