import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * ZTR-1154 push delivered-envelope golden — FCM/Mozilla (data.type_data) cleartext shape.
 * Digests are of the committed files under goldens/push/; verify.ts recomputes them.
 *
 * originKind is canonical-constructor (honest supersession of the ticket's
 * "real captured" AC): nesting is frozen from the merchant D8.92 / wallet-SW
 * delivered shape, not a live post-decrypt FCM/APNs capture. See meta.json
 * provenance.ac_claim.
 */

export const PUSH_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "push/delivered-envelope.data.v1",
    byteClass: "unsigned-evidence",
    indexPath: "goldens/push/delivered-envelope.data.v1.meta.json",
    files: [
      {
        path: "goldens/push/delivered-envelope.data.v1.meta.json",
        sha256: "262b54c485efc328ed2ff48d3d3b3657b94559cf5d53995df2e4273025b897a0",
      },
      {
        path: "goldens/push/delivered-envelope.data.v1.json.txt",
        sha256: "5528e5a101730d3766d4af96ea8cbc7998fb63575fe0b5d5d93a76400df02f42",
      },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod:
        "Offline golden-writer (quarantined per the golden regeneration and quarantine convention — no committed test writes a golden) " +
        "assembling the DELIVERED Web Push cleartext nesting from the merchant wallets D8.92 fixture " +
        "(apps/node/src/receivers/push/route.test.ts notificationBody: title/body + data.{id,type_name,type_data}) " +
        "and the wallet service-worker FCM/Mozilla branch (zucoins-wallet-mirror service-worker.js §505-543), " +
        "embedding the already-pinned RECEIVE transfer-code golden as transfer_code_encoded. " +
        "NOT a live post-decrypt FCM/APNs capture — no production subscription was available; " +
        "originKind is canonical-constructor (honest supersession of the ticket's 'real captured' AC). " +
        "Hand-verified against resolveTransferCodeFromEnvelope data-branch precedence; bytes committed with no trailing newline.",
      captureDate: "2026-08-11",
      walletVersion:
        "v200.6 (wallet coupling audit 2026-08-06/07; SW nesting + merchant D8.92 2026-07-16)",
      source:
        "merchant D8.92 delivered-envelope constructor + wallet SW FCM/Mozilla nest; " +
        "transfer_code_encoded = goldens/transfer-code/receive-code.v1.b64url.txt",
      keyMaterial:
        "none for the envelope itself; embedded transfer code uses deterministic test-only Ed25519 seeds 02/03 (never live ZKZ)",
      specCitations: [
        "packages/node-core/src/push/payload.ts — DELIVERED Web Push payload shape precedence",
        "Zucoins Merchant Wallets D8.92 — canonical DELIVERED Web Push payload shape",
        "zucoins-wallet-mirror service-worker.js §505-543 — FCM/Mozilla data.type_data branch",
        "ZTR-1154 — pin push envelope golden (canonical-constructor supersession) + alert on no_transfer_code run",
        "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
      ],
      decisionRefs: ["push-delivered-envelope-shape", "transfer-code-encoding-rule", "D8.92"],
      details: {
        golden: "DELIVERED Web Push cleartext — FCM/Mozilla data.type_data shape (full SW nest)",
        shape: "data",
        shapes_captured: "data",
        shapes_not_captured: "aps,send_side_fallback",
        origin_kind_note:
          "canonical-constructor, not wallet-capture — no live post-decrypt ciphertext was obtainable",
        sanitisation:
          "transfer_code_encoded substituted with digest-pinned RECEIVE transfer-code golden (non-live)",
        type_name: "transfer_code__v1",
      },
    },
  },
];
