import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * ZTR-1154 push delivered-envelope golden — FCM/Mozilla (data.type_data) cleartext shape.
 * Digests are of the committed files under goldens/push/; verify.ts recomputes them.
 */

export const PUSH_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "push/delivered-envelope.data.v1",
    byteClass: "unsigned-evidence",
    indexPath: "goldens/push/delivered-envelope.data.v1.meta.json",
    files: [
      {
        path: "goldens/push/delivered-envelope.data.v1.meta.json",
        sha256: "67e00793fc00064d33ca55877c7c3345c002a47548e988cba130b0194a032b38",
      },
      {
        path: "goldens/push/delivered-envelope.data.v1.json.txt",
        sha256: "936d81f42de6beebd93493565bceca995aa67514aea6e23205bfb74657a220b5",
      },
    ],
    provenance: {
      originKind: "wallet-capture",
      captureMethod:
        "Offline golden-writer (quarantined per the golden regeneration and quarantine convention — no committed test writes a golden) " +
        "assembling the delivered Web Push cleartext nesting documented by packages/node-core/src/push/payload.ts " +
        "(FCM/Mozilla data.type_data) and embedding the already-pinned RECEIVE transfer-code golden as transfer_code_encoded. " +
        "Hand-verified against resolveTransferCodeFromEnvelope data-branch precedence; bytes committed with no trailing newline.",
      captureDate: "2026-08-11",
      walletVersion:
        "v200.6 (wallet coupling audit 2026-08-06/07; shape confirmed against wallet SW nesting)",
      source:
        "wallet delivered-envelope reshape (post-decrypt cleartext); transfer_code_encoded = goldens/transfer-code/receive-code.v1.b64url.txt",
      keyMaterial:
        "none for the envelope itself; embedded transfer code uses deterministic test-only Ed25519 seeds 02/03 (never live ZKZ)",
      specCitations: [
        "packages/node-core/src/push/payload.ts — DELIVERED Web Push payload shape precedence",
        "ZTR-1154 — pin push envelope with real captured golden; alert on no_transfer_code run",
        "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
      ],
      decisionRefs: ["push-delivered-envelope-shape", "transfer-code-encoding-rule"],
      details: {
        golden: "DELIVERED Web Push cleartext — FCM/Mozilla data.type_data shape",
        shape: "data",
        shapes_captured: "data",
        shapes_not_captured: "aps,send_side_fallback",
        sanitisation:
          "transfer_code_encoded substituted with digest-pinned RECEIVE transfer-code golden (non-live)",
      },
    },
  },
];
