import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * A.8.3 SEND_EXTERNAL redemption golden (ZTR-1174) — offline re-sign of A.8.0 inner with
 * expiry floor(formation)+SEND_REDEMPTION_WINDOW_SECS. Digests pinned; no committed test
 * writes these bytes.
 */

export const SEND_REDEMPTION_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "send-redemption/a83-send-external-redemption",
    byteClass: "signed-preimage",
    indexPath: "goldens/send-redemption/a83-send-external-redemption.meta.json",
    files: [
      {
        path: "goldens/send-redemption/a83-send-external-redemption.meta.json",
        sha256: "b12ea5e0d2660c662930c64d806405a8ca908ece80558a4369f236296d0a3338",
      },
      {
        path: "goldens/send-redemption/a83-send-external-redemption.step1.preimage.txt",
        sha256: "46ba7528a9a757bd2bf50e2950256663aae9d20a51b485b71d511ac74b38662d",
      },
      {
        path: "goldens/send-redemption/a83-send-external-redemption.step1.sig.b64",
        sha256: "9dd70743c49a0a83392cf6e2acbc706a24066957a454d8a54be66c261c857bf4",
      },
    ],
    provenance: {
      originKind: "canonical-constructor",
      captureMethod:
        "Offline re-sign of A.8.0 inner with expiry 1784333100 (= formation 1784332800 + " +
        "SEND_REDEMPTION_WINDOW_SECS 300). Quarantined writer; no committed test writes this golden.",
      captureDate: "2026-08-11",
      walletVersion: "n/a — offline canonical constructor; no wallet capture",
      source:
        "A.8.0 SEND partial inner re-signed for A.8.3 SEND_EXTERNAL redemption window; " +
        "bytes under goldens/send-redemption/",
      keyMaterial:
        "deterministic test-only Ed25519 seeds 02 (sender) and 03 (receiver); MUST never be used with live ZKZ",
      specCitations: [
        "protocol foundation A.8.3 SEND_EXTERNAL redemption golden",
        "ZTR-1174 / ZTR-149 / GN-016.3",
        "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
      ],
      decisionRefs: ["send-redemption-window", "transfer-code-encoding-rule"],
      details: {
        golden: "A.8.3 SEND_EXTERNAL redemption step-1 preimage + signature",
        expiry__unix_time_secs: "1784333100",
        formation_unix_time_secs: "1784332800",
        SEND_REDEMPTION_WINDOW_SECS: "300",
      },
    },
  },
];
