import type { FixtureProvenanceRecord } from "../types.ts";

/**
 * the receive-golden transfer-code concern.3 transfer-code goldens — the wallet-capture provenance case. Provenance fields
 * generalize the sibling `*.v1.meta.json` sidecars (kept on disk as the human-readable
 * capture evidence; the registry digests them like every other family file).
 */

const WALLET_MIRROR =
  "live-wallet mirror capture: splitchain.js (full-site wallet clone; mirror not part of this repository)";

const TRANSFER_CODE_CAPTURE_METHOD =
  "Scratch golden-writer (quarantined per the golden regeneration and quarantine convention — no committed test writes a golden) " +
  "encoding the deterministic test step-1 preimage and step_1_signature verbatim through the wallet encode pipeline " +
  "(JSON.stringify -> encodeURIComponent -> base64url -> strip '='); encoded bytes verified byte-identical " +
  "between Node Buffer base64url and libsodium-wrappers@0.7.16 to_base64(URLSAFE) with padding stripped, and " +
  "round-trip decode verified via both implementations";

const TRANSFER_CODE_WALLET_VERSION =
  "not recorded by the capture — provenance anchors the live-wallet mirror file and exact line ranges instead";

const TRANSFER_CODE_SOURCE =
  "canonical-fields reference: deterministic test vectors (step-1 preimage + step_1_signature verbatim)";

const TRANSFER_CODE_KEY_MATERIAL =
  "deterministic test-only Ed25519 seeds 02 (sender) and 03 (receiver); MUST never be used with live ZKZ";

const TRANSFER_CODE_SPEC_CITATIONS = [
  "canonical-fields reference: deterministic test key material and expected outputs",
  "protocol foundation: signed-preimage byte class",
  "build-test plan: expected bytes are stored frozen, never regenerated by the implementation under test",
] as const;

const TRANSFER_CODE_DECISION_REFS = [
  "transfer-code-encoding-rule",
  "sender-code-v1-template-rule",
  "push-label-transfer-code-v1-rule",
  "transfer-code-version-coupling-rule",
  "expired-code-hard-reject-rule",
] as const;

const TRANSFER_CODE_WALLET_LINES = {
  encode_transfer_code: "splitchain.js:1791-1868",
  filter_transfer_code_structure__v1: "splitchain.js:1647-1789",
  filter_transaction_structure__v2: "splitchain.js:4067-4200",
} as const;

export const TRANSFER_CODE_FIXTURE_RECORDS: readonly FixtureProvenanceRecord[] = [
  {
    fixtureId: "transfer-code/receive-code.v1",
    byteClass: "signed-preimage",
    indexPath: "goldens/transfer-code/receive-code.v1.meta.json",
    files: [
      { path: "goldens/transfer-code/receive-code.v1.meta.json", sha256: "843f306c48364881743606631f4c2fa5ef311cbee1e9057546876761d97d23db" },
      { path: "goldens/transfer-code/receive-code.v1.json.txt", sha256: "6884acef681a435f7ef04b82c0d6d5df28c8f12275c2c69063d721ae6dcd0869" },
      { path: "goldens/transfer-code/receive-code.v1.b64url.txt", sha256: "104eb00c3bda958b82b7ce5a24e582dd9efa3e63d2192838fe26b5b23dcb2bab" },
    ],
    provenance: {
      originKind: "wallet-capture",
      captureMethod: TRANSFER_CODE_CAPTURE_METHOD,
      captureDate: "2026-07-19",
      walletVersion: TRANSFER_CODE_WALLET_VERSION,
      source: TRANSFER_CODE_SOURCE,
      keyMaterial: TRANSFER_CODE_KEY_MATERIAL,
      specCitations: TRANSFER_CODE_SPEC_CITATIONS,
      decisionRefs: TRANSFER_CODE_DECISION_REFS,
      details: {
        golden: "RECEIVE = sender_create_transaction v1 (non-explicit)",
        wallet_mirror: WALLET_MIRROR,
        "wallet_lines.encode_transfer_code": TRANSFER_CODE_WALLET_LINES.encode_transfer_code,
        "wallet_lines.filter_transfer_code_structure__v1": TRANSFER_CODE_WALLET_LINES.filter_transfer_code_structure__v1,
        "wallet_lines.filter_transaction_structure__v2": TRANSFER_CODE_WALLET_LINES.filter_transaction_structure__v2,
      },
    },
  },
  {
    fixtureId: "transfer-code/send-code.v1",
    byteClass: "signed-preimage",
    indexPath: "goldens/transfer-code/send-code.v1.meta.json",
    files: [
      { path: "goldens/transfer-code/send-code.v1.meta.json", sha256: "7baee2797c1fe7ce403f99d415e81dce1852d4ea52e16b2b4a188ee3da15a120" },
      { path: "goldens/transfer-code/send-code.v1.json.txt", sha256: "fc0af28b7232f2b83df93a39dac0bd1ddedcd477e658af23b49de49e3ed09640" },
      { path: "goldens/transfer-code/send-code.v1.b64url.txt", sha256: "d454846fddc861c059476553ec4fe03fdbf3cb494a0b5be6357ceb8049d6d0e4" },
    ],
    provenance: {
      originKind: "wallet-capture",
      captureMethod: TRANSFER_CODE_CAPTURE_METHOD,
      captureDate: "2026-07-19",
      walletVersion: TRANSFER_CODE_WALLET_VERSION,
      source: TRANSFER_CODE_SOURCE,
      keyMaterial: TRANSFER_CODE_KEY_MATERIAL,
      specCitations: TRANSFER_CODE_SPEC_CITATIONS,
      decisionRefs: TRANSFER_CODE_DECISION_REFS,
      details: {
        golden: "SEND = receiver_confirm_partial_transaction v1 (partial: step_2_signature omitted)",
        wallet_mirror: WALLET_MIRROR,
        "wallet_lines.encode_transfer_code": TRANSFER_CODE_WALLET_LINES.encode_transfer_code,
        "wallet_lines.filter_transfer_code_structure__v1": TRANSFER_CODE_WALLET_LINES.filter_transfer_code_structure__v1,
        "wallet_lines.filter_transaction_structure__v2": TRANSFER_CODE_WALLET_LINES.filter_transaction_structure__v2,
      },
    },
  },
];
