import { beforeAll, describe, expect, it } from "vitest";

import {
  ready,
  keypairFromSeedByte,
  encodeBase64Url,
  digestPreimage,
  signPreimage,
  verifyPreimageSignature,
  type RawKeypair,
} from "../testkit/independentCrypto.ts";
import { readGoldenText, sha256OfGolden } from "../testkit/byteGolden.ts";
import { defaultSuiteVerificationCrypto } from "../testkit/suiteVerificationCrypto.ts";
import { verifyExpectedArtifact, type ArtifactEnvelope } from "./verify.ts";
import { type NodeIdentityKeyRecord } from "./signing-contract.ts";
import { EXPECTED_ARTIFACT_PURPOSES, type ExpectedArtifactPurpose } from "./expected-artifacts.contract.ts";

/**
 * The wallet-faithfulness proof . An INDEPENDENT implementation
 * (`src/testkit/independentCrypto.ts`, pinned to the wallet's libsodium family) re-derives the
 * node identity key from the published deterministic seed byte 0x00 and reproduces every pinned
 * SHA-256 and Ed25519 signature in A.8 from the raw preimage goldens on disk. The
 * goldens are never regenerated by this code — they are read and asserted against.
 *
 * NODE_IDENTITY_SEED_BYTE keys are test-only and MUST never be used with live ZKZ (A.8, A.9(19)).
 */
const NODE_IDENTITY_SEED_BYTE = 0x00;

let nodeKeypair: RawKeypair;

beforeAll(async () => {
  await ready();
  nodeKeypair = keypairFromSeedByte(NODE_IDENTITY_SEED_BYTE);
});

const nodeKeyRecord = (publicKeyB64: string): NodeIdentityKeyRecord => ({
  keyId: "node-identity-golden",
  role: "node_identity",
  publicKeyB64,
  status: "ACTIVE",
  validFromUnixMs: 0,
  validUntilUnixMs: null,
});

describe("A.8 deterministic reproduction proof (artifacts)", () => {
  it("reproduces the pinned node identity public key from seed byte 0x00", () => {
    const goldenPub = readGoldenText("artifacts/node-identity.pub.b64");
    expect(encodeBase64Url(nodeKeypair.publicKey)).toBe(goldenPub);
    expect(goldenPub).toBe("O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=");
  });

  for (const purpose of EXPECTED_ARTIFACT_PURPOSES) {
    describe(purpose, () => {
      const preimage = () => readGoldenText(`artifacts/${purpose}.preimage.txt`);
      const pinnedDigest = () => readGoldenText(`artifacts/${purpose}.digest.hex`);
      const pinnedSig = () => readGoldenText(`artifacts/${purpose}.sig.b64`);

      it("preimage's domain-separation prefix is the purpose", () => {
        expect(preimage().slice(0, preimage().indexOf("\n"))).toBe(purpose);
      });

      it("reproduces the pinned SHA-256 digest from the exact preimage bytes", () => {
        expect(digestPreimage(preimage())).toBe(pinnedDigest());
      });

      it("the preimage file's own SHA-256 equals the pinned artifact digest (A.8 invariant)", () => {
        expect(sha256OfGolden(`artifacts/${purpose}.preimage.txt`)).toBe(pinnedDigest());
      });

      it("reproduces the pinned Ed25519 signature (wallet-faithfulness)", () => {
        expect(signPreimage(preimage(), nodeKeypair.privateKey)).toBe(pinnedSig());
      });

      it("the pinned signature verifies against the reproduced node public key", () => {
        expect(verifyPreimageSignature(preimage(), pinnedSig(), nodeKeypair.publicKey)).toBe(true);
      });

      it("passes the full artifact verifier end-to-end", async () => {
        const goldenPub = readGoldenText("artifacts/node-identity.pub.b64");
        const envelope: ArtifactEnvelope = {
          key_id: "node-identity-golden",
          preimage_text: preimage(),
          preimage_sha256: pinnedDigest(),
          signature: pinnedSig(),
        };
        const result = await verifyExpectedArtifact({
          envelope,
          key: nodeKeyRecord(goldenPub),
          signedAtUnixMs: 1_752_796_800_000,
          expectedPurpose: purpose as ExpectedArtifactPurpose,
          pinnedPublicKeyB64: goldenPub,
        }, defaultSuiteVerificationCrypto);
        expect(result).toEqual({ ok: true, purpose, digest: pinnedDigest() });
      });
    });
  }
});
