/**
 * Role-relative wallet state (protocol rule 5); A.8.1 (role-relative terminal projection
 * tables of the golden fixture chain).
 *
 * the fixture-provenance purposes census — the role-projection manifest category: the role predicates, the S/P/B projection
 * table, the succession rule, and the A.8.1 role-relative terminal-projection goldens (the
 * "role-relative head fixtures" the adversarial-fixture gate names). DATA ONLY so `gen/role-projections.json` stays a
 * clean review-diff snapshot. The genesis projection (`S=P=""`, `B="0"`) is OWNED by
 * `genesis.contract.ts`; the goldens' bytes are pinned by the fixture-provenance surface provenance registry
 * (`receive-golden/gen`).
 */

/** Manifest version (v1 `*_CONTRACT_VERSION` discipline): bump on any reviewed change. */
export const ROLE_PROJECTIONS_CONTRACT_VERSION = 1 as const;

/** The two transaction roles a wallet can hold (protocol rule 5). Exactly one predicate MUST hold for a
 *  queried wallet; self-transfers and a wallet absent from both positions are rejected. */
export const WALLET_TRANSACTION_ROLES = ["sender", "receiver"] as const;

/** The role predicates (protocol rule 5). */
export const ROLE_PREDICATES = {
  sender: "T.inner.step_1_key_public__base64urlsafe == W",
  receiver: "T.inner.step_2_key_public__base64urlsafe == W",
  exactlyOneMustHold: true,
  selfTransferRejected: true,
  absentWalletRejected: true,
} as const;

/**
 * The role-relative projection table (protocol rule 5), transcribed verbatim: `S` is the settled
 * `step_2_signature` for BOTH roles; `P` and `B` read the role's own side of the inner.
 * Never hard-code the receiver's `previous_step_2_state_signature` for a sender-side
 * observation (protocol rule 5 closing note).
 */
export const ROLE_RELATIVE_PROJECTIONS = [
  { value: "S", sender: "T.step_2_signature", receiver: "T.step_2_signature" },
  {
    value: "P",
    sender: "T.inner.previous_step_1_state_signature",
    receiver: "T.inner.previous_step_2_state_signature",
  },
  { value: "B", sender: "T.inner.step_1_state.amount", receiver: "T.inner.step_2_state.amount" },
] as const;

/** The succession rule (protocol rule 5): a successor for wallet W links its predecessor to the prior
 *  head's state signature. A complete landing path chains `P(W,Li) == S(W,L[i-1])` per hop. */
export const SUCCESSION_RULE = "P(W,T1) == S(W,T0)" as const;

/** Baseline/observation names (protocol rule 5): roles, not database columns tied to an operation number. */
export const OBSERVATION_NAME_SETS = {
  baselineAtIssuance: ["S0", "P0", "B0"],
  laterAccepted: ["S1", "P1", "B1"],
  namesAreRolesNotColumns: true,
} as const;

/** The genesis projection row (owned by `genesis.contract.ts`; restated as the projection-table
 *  terminal so the category reads complete). */
export const GENESIS_PROJECTION = { S: "", P: "", B: "0" } as const;

const PREDECESSOR_STEP_2_SIGNATURE =
  "IfsGs-NrmBAQ6VWohtlXDcyrd830Agx1IzW8rcHiqYqndeGLoG8b297PjqC-grrIXFrl3GgDcV2qi6xJBlerCQ==";
const PREDECESSOR_FUNDED_BOUNDARY_SIGNATURE =
  "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQ==";
const TARGET_STEP_2_SIGNATURE =
  "uP0HeCG-ZT1svQK-drwexhc1mrxx4QLBdfgFlw8nqRrwwvcJcPazgcPxp8aMdz7iJricO75II0bUzvwlBUUDDw==";

/**
 * The A.8.1 role-relative terminal-projection goldens, transcribed verbatim from the two
 * fixture tables. These are EXPECTATIONS the projection rules must reproduce from the
 * provenance-registered fixture bytes (`src/receive-golden/gen/*.settled.json`, the fixture-provenance surface
 * `receive-golden/gen`) — never regenerated by the code under test (the adversarial-fixture gate).
 */
export const ROLE_RELATIVE_TERMINAL_PROJECTION_GOLDENS = [
  {
    fixture: "A.8.1 predecessor",
    settledBytes: "src/receive-golden/gen/predecessor.settled.json",
    walletRole: "sender",
    wallet: "seed-05",
    S: PREDECESSOR_STEP_2_SIGNATURE,
    P: PREDECESSOR_FUNDED_BOUNDARY_SIGNATURE,
    B: "0",
  },
  {
    fixture: "A.8.1 predecessor",
    settledBytes: "src/receive-golden/gen/predecessor.settled.json",
    walletRole: "receiver",
    wallet: "seed-02",
    S: PREDECESSOR_STEP_2_SIGNATURE,
    P: "",
    B: "10",
  },
  {
    fixture: "A.8.1 target",
    settledBytes: "src/receive-golden/gen/target.settled.json",
    walletRole: "sender",
    wallet: "seed-02",
    S: TARGET_STEP_2_SIGNATURE,
    P: PREDECESSOR_STEP_2_SIGNATURE,
    B: "7.75",
  },
  {
    fixture: "A.8.1 target",
    settledBytes: "src/receive-golden/gen/target.settled.json",
    walletRole: "receiver",
    wallet: "seed-03",
    S: TARGET_STEP_2_SIGNATURE,
    P: "",
    B: "2.25",
  },
] as const;

export const SOURCE = "role-relative projections; A.8.1; complete-path-adjudication" as const;
