import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { assertFieldOrder, expectRejects } from "../testkit/freeze.ts";
import {
  GENESIS_PROJECTION,
  OBSERVATION_NAME_SETS,
  ROLE_PREDICATES,
  ROLE_PROJECTIONS_CONTRACT_VERSION,
  ROLE_RELATIVE_PROJECTIONS,
  ROLE_RELATIVE_TERMINAL_PROJECTION_GOLDENS,
  SUCCESSION_RULE,
  WALLET_TRANSACTION_ROLES,
} from "./role-projections.contract.ts";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

interface SettledTransaction {
  readonly inner: {
    readonly step_1_key_public__base64urlsafe: string;
    readonly step_2_key_public__base64urlsafe: string;
    readonly step_1_state: { readonly amount: string };
    readonly step_2_state: { readonly amount: string };
    readonly previous_step_1_state_signature: string;
    readonly previous_step_2_state_signature: string;
  };
  readonly step_1_signature: string;
  readonly step_2_signature: string;
}

const readSettled = (relativePath: string): SettledTransaction =>
  JSON.parse(readFileSync(join(packageRoot, relativePath), "utf8")) as SettledTransaction;

/** The protocol rule 5 role-relative projection, derived from settled bytes — the check the frozen
 *  golden rows must equal (expectations never regenerated by the code under test, the adversarial-fixture gate). */
const project = (
  settled: SettledTransaction,
  role: "sender" | "receiver",
): { S: string; P: string; B: string } => ({
  S: settled.step_2_signature,
  P:
    role === "sender"
      ? settled.inner.previous_step_1_state_signature
      : settled.inner.previous_step_2_state_signature,
  B: role === "sender" ? settled.inner.step_1_state.amount : settled.inner.step_2_state.amount,
});

/** The protocol rule 5 role predicate: exactly one of sender/receiver must hold. */
const assertRole = (
  inner: SettledTransaction["inner"],
  wallet: string,
): "sender" | "receiver" => {
  const isSender = inner.step_1_key_public__base64urlsafe === wallet;
  const isReceiver = inner.step_2_key_public__base64urlsafe === wallet;
  if (isSender === isReceiver) {
    throw new Error("exactly one role predicate must hold");
  }
  return isSender ? "sender" : "receiver";
};

describe("role-projections census (the fixture-provenance purposes census, protocol rule 5; A.8.1)", () => {
  it("freezes the two transaction roles and the role predicates", () => {
    assertFieldOrder(WALLET_TRANSACTION_ROLES, ["sender", "receiver"]);
    expect(ROLE_PREDICATES.sender).toBe("T.inner.step_1_key_public__base64urlsafe == W");
    expect(ROLE_PREDICATES.receiver).toBe("T.inner.step_2_key_public__base64urlsafe == W");
    expect(ROLE_PREDICATES.exactlyOneMustHold).toBe(true);
    expect(ROLE_PREDICATES.selfTransferRejected).toBe(true);
    expect(ROLE_PREDICATES.absentWalletRejected).toBe(true);
  });

  it("freezes the S/P/B projection table (S role-independent; P/B role-side)", () => {
    assertFieldOrder(
      ROLE_RELATIVE_PROJECTIONS.map((row) => row.value),
      ["S", "P", "B"],
    );
    const [s, p, b] = ROLE_RELATIVE_PROJECTIONS;
    expect(s.sender).toBe("T.step_2_signature");
    expect(s.receiver).toBe("T.step_2_signature");
    expect(p.sender).toBe("T.inner.previous_step_1_state_signature");
    expect(p.receiver).toBe("T.inner.previous_step_2_state_signature");
    expect(b.sender).toBe("T.inner.step_1_state.amount");
    expect(b.receiver).toBe("T.inner.step_2_state.amount");
  });

  it("freezes the succession rule and the observation name sets", () => {
    expect(SUCCESSION_RULE).toBe("P(W,T1) == S(W,T0)");
    assertFieldOrder(OBSERVATION_NAME_SETS.baselineAtIssuance, ["S0", "P0", "B0"]);
    assertFieldOrder(OBSERVATION_NAME_SETS.laterAccepted, ["S1", "P1", "B1"]);
    expect(OBSERVATION_NAME_SETS.namesAreRolesNotColumns).toBe(true);
  });

  it("freezes the genesis projection row", () => {
    expect(GENESIS_PROJECTION).toEqual({ S: "", P: "", B: "0" });
  });

  it("the A.8.1 terminal-projection goldens derive from the provenance-registered bytes", () => {
    for (const golden of ROLE_RELATIVE_TERMINAL_PROJECTION_GOLDENS) {
      const derived = project(readSettled(golden.settledBytes), golden.walletRole);
      expect({ S: derived.S, P: derived.P, B: derived.B }, `${golden.fixture} ${golden.walletRole}`).toEqual({
        S: golden.S,
        P: golden.P,
        B: golden.B,
      });
    }
  });

  it("the target's sender P backlinks the predecessor's settled step_2_signature (protocol rule 5)", () => {
    const predecessor = readSettled("src/receive-golden/gen/predecessor.settled.json");
    const target = readSettled("src/receive-golden/gen/target.settled.json");
    expect(target.inner.previous_step_1_state_signature).toBe(predecessor.step_2_signature);
  });

  it("rejects a self-transfer (both predicates hold, negative path)", () => {
    const settled = readSettled("src/receive-golden/gen/target.settled.json");
    const selfInner = {
      ...settled.inner,
      step_2_key_public__base64urlsafe: settled.inner.step_1_key_public__base64urlsafe,
    };
    expectRejects(
      () => settled.inner.step_1_key_public__base64urlsafe,
      (wallet) => void assertRole(selfInner, wallet),
    );
  });

  it("rejects an absent wallet (neither predicate holds, negative path)", () => {
    const settled = readSettled("src/receive-golden/gen/target.settled.json");
    expectRejects(
      () => "bnoc3Smwt4_ROvTFWY_v9O8qlxZuPKby5Pv8zYBQW_E=",
      (wallet) => void assertRole(settled.inner, wallet),
    );
  });

  it("rejects a cross-role P substitution (receiver P read for the sender, negative path)", () => {
    const target = readSettled("src/receive-golden/gen/target.settled.json");
    const senderGolden = ROLE_RELATIVE_TERMINAL_PROJECTION_GOLDENS.find(
      (golden) => golden.fixture === "A.8.1 target" && golden.walletRole === "sender",
    );
    const crossRoleP = target.inner.previous_step_2_state_signature;
    expect(crossRoleP).not.toBe(senderGolden?.P);
    expectRejects(
      () => crossRoleP,
      (mutated) => assertFieldOrder([mutated], [senderGolden?.P ?? ""]),
    );
  });

  it("pins the manifest version", () => {
    expect(ROLE_PROJECTIONS_CONTRACT_VERSION).toBe(1);
  });
});
